const fs=require('node:fs');
const path=require('node:path');
const root=__dirname;
const {PLUM_DESIGNS:designs}=require('./plum-model.js');
const {plumDefaults,plumFilename,plumSnippet,plumMarkup}=require('./plum-model.js');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const revision=fs.existsSync(path.join(root,'stylesheet-revision.txt'))?read('stylesheet-revision.txt').trim():'main';
if(!/^(main|[a-f0-9]{40})$/.test(revision))throw new Error('Invalid stylesheet revision');
const svg=(viewBox,body)=>`<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}">${body}</svg>`;
const blossom=(x,y,r=1)=>`<g transform="translate(${x} ${y}) scale(${r})" fill="none" stroke="black" stroke-width="1.25"><ellipse cy="-7" rx="4" ry="7"/><ellipse cy="-7" rx="4" ry="7" transform="rotate(72)"/><ellipse cy="-7" rx="4" ry="7" transform="rotate(144)"/><ellipse cy="-7" rx="4" ry="7" transform="rotate(216)"/><ellipse cy="-7" rx="4" ry="7" transform="rotate(288)"/><circle r="2" fill="black"/></g>`;
const masks={branch:svg('0 0 160 74','<g fill="none" stroke="black" stroke-width="1.2"><path d="M4 62C42 52 93 46 151 7M31 54L26 30M54 48Q68 32 63 14M89 36L103 57M125 24L121 8M31 54Q16 47 14 38Q28 39 31 54M89 36Q93 21 105 18Q103 32 89 36"/></g>'+blossom(28,26,.6)+blossom(64,15,.7)+blossom(103,58,.52)+blossom(139,13,.66)),blossom:svg('0 0 70 44',blossom(33,22,1.25)+'<path d="M7 25Q16 19 20 24M46 24Q54 20 63 13" fill="none" stroke="black"/>'),stone:svg('0 0 64 94','<g fill="none" stroke="black" stroke-width="1.2"><path d="M32 9C9-1 1 22 6 52C9 75 24 86 32 90C51 82 62 61 60 34C58 12 48 2 32 9Z"/><path d="M33 11C23 34 23 62 32 88M36 7Q40 1 47 2M16 29Q9 42 16 58M21 23Q12 44 24 71M47 26Q57 47 43 71M40 24Q50 45 36 78"/></g>')};
const maskRules='.plm{'+Object.entries(masks).map(([key,value])=>`--plm-${key}:url("data:image/svg+xml,${encodeURIComponent(value)}");`).join('')+'}';
const css=read('plum-fonts.css')+'\n'+maskRules+'\n'+read('plum-source.css');
fs.writeFileSync(path.join(root,'plum-lasting-season-v1.css'),css);
fs.writeFileSync(path.join(root,'designs.json'),JSON.stringify(designs,null,2)+'\n');
for(const d of designs)fs.writeFileSync(path.join(root,plumFilename(d)),plumSnippet(d,plumDefaults(d),revision));
const preview=`<!doctype html>
<html lang="en" color-mode="light">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Plum · Fifteen JCink Templates</title><meta name="description" content="Five threads, five comms and five buds. Preview, edit and copy the Plum collection."><style>${read('plum-preview.css')}</style><style>${read('plum-lasting-season-v1.css')}</style></head>
<body>
<header class="pv-top"><h1 class="pv-brand">Plum</h1><div class="pv-sub">THE LASTING SEASON<br>05 THREADS · 05 COMMS · 05 BUDS</div><div class="pv-toolbar"><label>Mode <select id="pv-mode"><option value="light">Light</option><option value="dark">Dark</option><option value="system">System</option></select></label><label>Members <select id="pv-palette"><option value="poster">Poster</option><option value="lagoon">Lagoon</option><option value="ember">Ember</option><option value="mono">Monochrome</option><option value="custom">Custom</option></select></label><div class="pv-colours"><input id="pv-colour-1" aria-label="Member colour 1" type="color" value="#7e4067"><input id="pv-colour-2" aria-label="Member colour 2" type="color" value="#7d6a99"><input id="pv-colour-3" aria-label="Member colour 3" type="color" value="#aa5a75"></div><label>Width <select id="pv-width"><option value="full">Full</option><option value="375">375 px</option><option value="320">320 px</option></select></label><button id="pv-view-all" aria-pressed="false">View all 15</button></div></header>
<main><div class="pv-workspace" id="pv-workspace"><nav class="pv-nav" id="pv-nav" aria-label="Plum designs"></nav><section class="pv-canvas" aria-label="Template preview"><div class="pv-caption"><div><h2 id="pv-design-title">Damson Vesper</h2><p id="pv-design-description"></p></div><div class="pv-stepper"><button id="pv-previous" aria-label="Previous design">‹</button><button id="pv-next" aria-label="Next design">›</button></div></div><div class="pv-stage" id="pv-stage">${plumMarkup(designs[0],plumDefaults(designs[0]))}</div></section><aside class="pv-editor" id="pv-editor"><h2>Edit & copy</h2><label class="pv-field">Name<input id="pv-name" value="[name]"></label><label class="pv-field"><span id="pv-title-label">Title</span><input id="pv-title" value="[text]"></label><label class="pv-field">Name link<input id="pv-url" value="[url]"></label><div class="pv-two" id="pv-device-fields" hidden><label class="pv-field">Time<input id="pv-time" value="22:14"></label><label class="pv-field">Messages<select id="pv-flow"><option value="received">Received</option><option value="sent">Sent</option><option value="mixed">Alternating</option></select></label></div><div id="pv-gifs"></div><button class="pv-add" id="pv-add-gif">Add GIF</button><label class="pv-field"><span class="pv-writing-label">Writing<span id="pv-word-count" class="pv-count"></span></span><textarea id="pv-body" spellcheck="false"></textarea></label><p class="pv-hint">Use ordinary &lt;p&gt; paragraphs. [b], [i] and [u] are converted to HTML when copied. Preview colours and mode stay outside your posting code.</p><div class="pv-actions"><button id="pv-copy" class="pv-primary">Copy JCink code</button><button id="pv-download">Download .txt</button></div><p class="pv-status" id="pv-status" role="status" aria-live="polite"></p><details id="pv-code-details"><summary>View posting code</summary><textarea class="pv-code" id="pv-code" readonly aria-label="JCink posting code" spellcheck="false"></textarea></details><button id="pv-reset" class="pv-reset">Reset this design</button><p class="pv-hint">Edits remain while this page is open. Download an edited snippet to keep it.</p></aside></div><section id="pv-gallery" class="pv-gallery" aria-label="All fifteen Plum designs" hidden></section></main>
<footer class="pv-footer"><span>Plum · The Lasting Season</span><a href="https://github.com/lexdoescodingnow/templates/tree/main/plum">GitHub collection</a><span>Member colours · Blue Hour light/dark · Ready for [dohtml]</span></footer>
<script type="application/json" id="plum-designs">${JSON.stringify(designs).replace(/</g,'\\u003c')}</script><script>const PLUM_REVISION=${JSON.stringify(revision)};${read('plum-model.js')}</script><script>${read('plum-editor.js')}</script>
</body></html>`;
fs.writeFileSync(path.join(root,'plum-collection-preview.html'),preview);
console.log(`Built ${designs.length} posting snippets and the standalone preview.`);
