const fs=require('node:fs');
const path=require('node:path');
const root=__dirname;
const designs=require('./designs.json');
const {lavenderDefaults,lavenderFilename,lavenderSnippet,lavenderMarkup}=require('./lavender-model.js');
const revisionPath=path.join(root,'stylesheet-revision.txt');
if(fs.existsSync(revisionPath)){const revision=fs.readFileSync(revisionPath,'utf8').trim();if(!/^[a-f0-9]{40}$/.test(revision))throw new Error('Invalid stylesheet revision');const modelPath=path.join(root,'lavender-model.js');const updated=fs.readFileSync(modelPath,'utf8').replace(/templates@(?:main|[a-f0-9]{40})\/lavender\//g,'templates@'+revision+'/lavender/');if(updated!==fs.readFileSync(modelPath,'utf8')){fs.writeFileSync(modelPath,updated);delete require.cache[require.resolve('./lavender-model.js')];require('node:child_process').execFileSync(process.execPath,[__filename],{stdio:'inherit'});process.exit(0);}}
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
for(const d of designs)fs.writeFileSync(path.join(root,lavenderFilename(d)),lavenderSnippet(d,lavenderDefaults(d)));
const preview=`<!doctype html>
<html lang="en" color-mode="light">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lavender · Fifteen JCink Templates</title><meta name="description" content="Five threads, five comms and five buds. Preview, edit and copy the Lavender collection."><style>${read('lavender-stillroom-v1.css')}</style><style>${read('lavender-preview.css')}</style></head>
<body>
<header class="pv-top"><h1 class="pv-brand">Lavender</h1><div class="pv-sub">JINWOO & YOHAN · THE STILLROOM COLLECTION<br>05 THREADS · 05 COMMS · 05 BUDS</div><div class="pv-toolbar"><label>Mode <select id="pv-mode"><option value="light">Light</option><option value="dark">Dark</option><option value="system">System</option></select></label><label>Members <select id="pv-palette"><option value="stillroom">Lavender</option><option value="lagoon">Lagoon</option><option value="ember">Ember</option><option value="mono">Monochrome</option><option value="custom">Custom</option></select></label><div class="pv-colours"><input id="pv-colour-1" aria-label="Member colour 1" type="color" value="#80689f"><input id="pv-colour-2" aria-label="Member colour 2" type="color" value="#587e88"><input id="pv-colour-3" aria-label="Member colour 3" type="color" value="#a56f86"></div><label>Width <select id="pv-width"><option value="full">Full</option><option value="375">375 px</option><option value="320">320 px</option></select></label><button id="pv-view-all" aria-pressed="false">View all 15</button></div></header>
<main><div class="pv-workspace" id="pv-workspace"><nav class="pv-nav" id="pv-nav" aria-label="Lavender designs"></nav><section class="pv-canvas" aria-label="Template preview"><div class="pv-caption"><div><h2 id="pv-design-title">Stillroom Nocturne</h2><p id="pv-design-description"></p></div><div class="pv-stepper"><button id="pv-previous" aria-label="Previous design">‹</button><button id="pv-next" aria-label="Next design">›</button></div></div><div class="pv-stage" id="pv-stage">${lavenderMarkup(designs[0],{...lavenderDefaults(designs[0]),name:'Jinwoo & Yohan',title:designs[0].sample,url:'#'})}</div></section><aside class="pv-editor" id="pv-editor"><h2>Edit & copy</h2><label class="pv-field">Name<input id="pv-name" value="[name]"></label><label class="pv-field"><span id="pv-title-label">Title</span><input id="pv-title" value="[text]"></label><label class="pv-field">Name link<input id="pv-url" value="[url]"></label><div class="pv-two" id="pv-device-fields" hidden><label class="pv-field">Time<input id="pv-time" value="22:08"></label><label class="pv-field">Messages<select id="pv-flow"><option value="received">Received</option><option value="sent">Sent</option><option value="mixed">Alternating</option></select></label></div><div id="pv-gifs"></div><button class="pv-add" id="pv-add-gif">Add GIF</button><label class="pv-field"><span class="pv-writing-label">Writing<span id="pv-word-count" class="pv-count"></span></span><textarea id="pv-body" spellcheck="false"></textarea></label><p class="pv-hint">Use ordinary &lt;p&gt; paragraphs. [b], [i] and [u] are converted to HTML when copied. Preview colours and mode stay outside your posting code.</p><div class="pv-actions"><button id="pv-copy" class="pv-primary">Copy JCink code</button><button id="pv-download">Download .txt</button></div><p class="pv-status" id="pv-status" role="status" aria-live="polite"></p><details id="pv-code-details"><summary>View posting code</summary><textarea class="pv-code" id="pv-code" readonly aria-label="JCink posting code" spellcheck="false"></textarea></details><button id="pv-reset" class="pv-reset">Reset this design</button><p class="pv-hint">Edits remain while this page is open. Download an edited snippet to keep it.</p></aside></div><section id="pv-gallery" class="pv-gallery" aria-label="All fifteen Lavender designs" hidden></section></main>
<footer class="pv-footer"><span>Lavender · The Stillroom collection</span><a href="https://github.com/lexdoescodingnow/templates/tree/main/lavender">GitHub collection</a><span>Member colours · Blue Hour light/dark · Ready for [dohtml]</span></footer>
<script type="application/json" id="lavender-designs">${JSON.stringify(designs).replace(/</g,'\\u003c')}</script><script>${read('lavender-model.js')}</script><script>${read('lavender-editor.js')}</script>
</body></html>`;
fs.writeFileSync(path.join(root,'lavender-collection-preview.html'),preview);
console.log(`Built ${designs.length} posting snippets and the standalone preview.`);
