const fs=require('node:fs');
const path=require('node:path');
const out=__dirname;
const cssURL='https://cdn.jsdelivr.net/gh/lexdoescodingnow/templates@main/potato/potato-earth-and-edge-v1.css';
const gifs=['https://64.media.tumblr.com/2233fe9916e9d3db90bcb337c900dd29/83ec6d47b0a2e6e9-b8/s400x600/cfcbb8400eb2b48d6207580913f410e16b0a41e4.gifv','https://64.media.tumblr.com/591bcef18a069f351441177466607e80/1a37daeaf473a555-33/s250x400/9164f4725ec7dc87ce6a210c0710f9c52193dc61.gifv'];
const writing={
thread:'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <b>“Aliquam erat volutpat.”</b> Pellentesque vel urna vitae libero blandit lacinia. Maecenas euismod, arcu vitae luctus vestibulum, nibh massa tempus felis, sed pretium sem mi nec augue.</p>\n<p>Donec vitae leo sit amet augue congue malesuada. <i>Nullam id nisi quis justo tincidunt interdum.</i> Sed suscipit, ipsum a volutpat elementum, ante neque luctus quam, at interdum turpis felis vitae metus. Integer non purus sed mi aliquam finibus.</p>\n<p>Curabitur id ligula ac augue sodales congue. <u>Praesent vel velit sed arcu.</u> Cras imperdiet lorem non augue posuere, eu eleifend justo finibus. Suspendisse potenti. Fusce euismod elit eget nibh interdum, sed egestas justo aliquet.</p>',
comms:'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>\n<p><b>Aliquam erat volutpat.</b> Donec vitae leo sit amet augue.</p>\n<p><i>Nullam id nisi quis justo.</i> <u>Praesent vel velit.</u></p>',
bud:'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <b>“Aliquam erat volutpat.”</b> Donec vitae leo sit amet augue congue malesuada. <i>Nullam id nisi quis justo</i> tincidunt interdum. <u>Praesent vel velit</u> sed arcu.</p>'};
const designs=[
['thread','Furrow & Fable','furrow-and-fable',1,'every road comes home','Minwoo / Phoenix / a place to begin',1],
['thread','Hasselback Hours','hasselback-hours',2,'a thousand little moments','side by side, time after time',2],
['thread','Foil Moon','foil-moon',2,'keep a little warmth for me','under the kitchen light',3],
['thread','Russet Press','russet-press',0,'the ordinary things we keep','a story in the margins',4],
['thread','Solanum Study','solanum-study',1,'rooted in the same place','there is room for us to grow',5],
['comms','Spudline','spudline',1,'Phoenix','online now',1],
['comms','Tater Text','tater-text',1,'Minwoo','message received',2],
['comms','Crinkle Chat','crinkle-chat',2,'Minwoo & Phoenix','private conversation',3],
['comms','Jacket Pocket','jacket-pocket',1,'Phoenix','three new messages',4],
['comms','Chit Circuit','chit-circuit',0,'Minwoo','signal connected',5],
['bud','Potato Eye','potato-eye',1,'just a little closer','a moment with you',1],
['bud','Wedgelet','wedgelet',0,'a small slice of time','here, for a little while',2],
['bud','Salt Fleck','salt-fleck',1,'the smallest of things','one last word',4],
['bud','Twin Tubers','twin-tubers',2,'you and me, again','from the same patch',3],
['bud','Rootbound Kiss','rootbound-kiss',0,'somewhere to stay','let it grow',5]
].map((d,i)=>({type:d[0],name:d[1],slug:d[2],images:d[3],sampleTitle:d[4],subtitle:d[5],motif:d[6],number:String(i%5+1).padStart(2,'0'),file:`potato-${d[2]}-${d[0]}-${String(i%5+1).padStart(2,'0')}.txt`}));
function esc(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');}
function defaults(d){return {name:'Minwoo & Phoenix',url:'[url]',title:d.sampleTitle,subtitle:d.subtitle,gif1:d.images?gifs[d.slug==='tater-text'||d.slug==='salt-fleck'?1:0]:'',gif2:d.images>1?gifs[1]:'',crop1:'50% 35%',crop2:'50% 35%',copy:writing[d.type],time:'21:08',receipt:'Delivered',direction:'received'};}
function art(n){
const tuber='<path d="M29 26C46 7 76 14 86 36C99 63 73 84 50 86C22 89 6 70 14 50C17 42 21 35 29 26Z" fill="currentColor" fill-opacity=".08" stroke="currentColor" stroke-width="1.5"/><path d="M31 43l3-2m26-8l3 2m8 25l-3 2M39 70l3 1m11-20l2 3" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>';
if(n===2)return '<svg viewBox="0 0 120 80" aria-hidden="true"><path d="M15 60Q13 21 57 18Q101 12 106 60Z" fill="currentColor" fill-opacity=".08" stroke="currentColor" stroke-width="1.5"/><path d="M28 59L34 28M41 59L47 22M55 59L61 21M69 59L75 23M83 59L87 30M96 58L98 41" stroke="currentColor" stroke-width="3"/><path d="M9 68H112" stroke="currentColor"/></svg>';
if(n===3)return '<svg viewBox="0 0 100 100" aria-hidden="true"><path d="M9 46L28 11L80 20L94 61L62 91L17 78Z" fill="currentColor" fill-opacity=".06" stroke="currentColor"/><path d="M9 46L53 36L28 11M53 36L94 61L62 91L53 36L17 78M53 36L80 20" fill="none" stroke="currentColor" stroke-opacity=".5"/><path d="M40 48Q52 37 66 49Q76 62 60 71Q40 80 33 66Q30 55 40 48Z" fill="currentColor" fill-opacity=".16" stroke="currentColor"/></svg>';
if(n===4)return '<svg viewBox="0 0 100 100" aria-hidden="true"><path d="M18 53L35 25L80 33L68 78L18 53Z" fill="currentColor" fill-opacity=".08" stroke="currentColor" stroke-width="1.5"/><path d="M18 53L62 60L80 33M62 60L68 78" fill="none" stroke="currentColor"/><path d="M17 20l2-4m66 45l4 1M34 82l2 3M58 15l3-2" stroke="currentColor" stroke-width="2"/></svg>';
if(n===5)return '<svg viewBox="0 0 100 120" aria-hidden="true"><g transform="translate(15 48) scale(.72)">'+tuber+'</g><path d="M52 76Q43 45 53 17M49 44Q20 40 25 21Q47 23 49 44ZM51 33Q51 9 76 13Q72 35 51 33Z" fill="none" stroke="currentColor" stroke-width="1.4"/><path d="M48 107L43 117M60 106L67 115" stroke="currentColor"/></svg>';
return '<svg viewBox="0 0 100 100" aria-hidden="true">'+tuber+'</svg>';
}
function template(d,s){
const media=[s.gif1,s.gif2].map((g,i)=>g?`<span class="pt1-shot"><img src="${esc(g)}" alt="Character GIF ${i+1}" style="--pt-crop:${esc(s['crop'+(i+1)])}"></span>`:'').filter(Boolean).join('\n');
const devices={
'spudline':['SPUDLINE','● ▰','Message…','↑'],
'tater-text':['TATER / SMS','▂ ▄ ▆','1　2　3　·　4　5　6','7　8　9　·　✳　0　#'],
'crinkle-chat':['CRINKLE','CONNECTED','Write a reply…','↗'],
'jacket-pocket':['JACKET POCKET','● ▰','Slide to reply','→'],
'chit-circuit':['CHIT CIRCUIT','▂ ▄ ▆','ENTER MESSAGE','↵']};
const c=devices[d.slug];
return `[dohtml]\n<div class="pt1 pt1-${d.type} pt1-${d.slug}"${d.type==='comms'?` data-direction="${esc(s.direction)}"`:''}>\n<div class="pt1-layout">\n<div class="pt1-head">\n<a class="pt1-name" href="${esc(s.url)}">${esc(s.name)}</a>\n<span class="pt1-title">${esc(s.title)}</span>\n<span class="pt1-sub">${esc(s.subtitle)}</span>\n</div>\n${media?`<div class="pt1-media">\n${media}\n</div>\n`:''}<div class="pt1-copy">\n${s.copy}\n</div>\n${c?`<div class="pt1-receipt"><span>${esc(s.time)}</span><span>${esc(s.receipt)}</span></div>\n`:''}<div class="pt1-art" aria-hidden="true">${art(d.motif)}</div>\n${c?`<div class="pt1-chrome" aria-hidden="true"><span>${c[0]}</span><span>${c[1]}</span></div>\n<div class="pt1-device" aria-hidden="true">${d.slug==='tater-text'?['1','2','3','4','5','6','7','8','9','✳','0','#'].map(k=>'<span>'+k+'</span>').join(''):`<span>${c[2]}</span><span>${c[3]}</span>`}</div>\n`:''}</div>\n</div>\n<link rel="stylesheet" href="${cssURL}">\n[/dohtml]`;
}
function bare(code){return code.replace(/\[\/?dohtml\]/gi,'').replace(/<link[^>]*>/gi,'');}
const css=fs.readFileSync(path.join(out,'layout.css'),'utf8');
fs.writeFileSync(path.join(out,'potato-earth-and-edge-v1.css'),css);
fs.writeFileSync(path.join(out,'designs.json'),JSON.stringify(designs,null,2)+'\n');
for(const d of designs)fs.writeFileSync(path.join(out,d.file),template(d,defaults(d))+'\n');
fs.writeFileSync(path.join(out,'potato-placeholder-masterpost.txt'),designs.map(d=>d.name+'\n\n'+template(d,{...defaults(d),name:'[name]',url:'[url]',title:'[text]'})).join('\n\n')+'\n');
const cards=designs.map(d=>{
const s=defaults(d),code=template(d,s);
const fields=[['name','Names'],['url','Link URL'],['title',d.type==='comms'?'Contact / conversation':'Title'],['subtitle',d.type==='comms'?'Status':'Subtitle'],['gif1','GIF 1 URL'],['gif2','GIF 2 URL'],['crop1','GIF 1 position'],['crop2','GIF 2 position'],...(d.type==='comms'?[['time','Time'],['receipt','Receipt']]:[])].map(([key,label])=>`<label>${label}<input name="${key}" value="${esc(s[key])}" spellcheck="false"></label>`).join('');
return `<section class="pt-card" id="${d.slug}" data-kind="${d.type}"><header class="pt-card-head"><span>${d.type==='bud'?'BUDS':d.type.toUpperCase()} / ${d.number}</span><h2>${esc(d.name)}</h2><a href="#top" aria-label="Back to top">↑</a></header><div class="pt-stage">${bare(code)}</div><details class="pt-editor"><summary>Edit this template</summary><form>${fields}${d.type==='comms'?'<label>Message direction<select name="direction"><option value="received">Received</option><option value="sent">Sent</option><option value="alternating">Alternating</option></select></label>':''}<label class="pt-writing">${d.type==='comms'?'Messages':'Writing'}<textarea name="copy" rows="7" spellcheck="false">${esc(s.copy)}</textarea></label><button class="pt-reset" type="button">Reset sample</button></form></details><div class="pt-actions"><button class="pt-copy" type="button">Copy template</button><button class="pt-placeholders" type="button">Copy [name] / [text] version</button><a href="${d.file}">GitHub snippet ↗</a><span class="pt-status" role="status"></span></div><textarea class="pt-code" aria-label="${esc(d.name)} posting code" readonly spellcheck="false">${esc(code)}</textarea></section>`;
}).join('\n');
const page=`<!doctype html>\n<html lang="en" color-mode="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Potato · Minwoo &amp; Phoenix</title><style>${css}\n${fs.readFileSync(path.join(out,'preview.css'),'utf8')}</style></head><body><main class="pt-main" id="top"><header class="pt-intro"><div class="pt-collection"><span>MINWOO &amp; PHOENIX</span><span>EARTH &amp; EDGE / 15 DESIGNS</span></div><div class="pt-masthead"><h1>Potato.</h1><span class="pt-emblem">${art(1)}</span></div><nav class="pt-toplinks"><a href="../forum-posts/potato-forum-masterpost.txt">Forum masterpost ↗</a><a href="potato-collection.zip">Download collection ↗</a><a href="README.md">Editing guide ↗</a></nav></header><nav class="pt-controls" aria-label="Preview controls"><div class="pt-filters"><button data-filter="all" aria-pressed="true">All 15</button><button data-filter="thread" aria-pressed="false">Threads</button><button data-filter="comms" aria-pressed="false">Comms</button><button data-filter="bud" aria-pressed="false">Buds</button></div><label>Appearance<select id="pt-mode"><option value="light">Light</option><option value="dark">Dark</option><option value="system">System</option></select></label><label>Width<select id="pt-width"><option value="full">Full</option><option value="390">390px</option><option value="320">320px</option><option value="260">260px</option></select></label><label>Member palette<select id="pt-palette"><option value="plum">Plum / jade</option><option value="blue">Blue / lilac</option><option value="copper">Copper / teal</option></select></label></nav>${cards}<footer class="pt-footer">POTATO / EARTH &amp; EDGE <a href="#top">Back to top ↑</a></footer></main><script>const designs=${JSON.stringify(designs)};const gifs=${JSON.stringify(gifs)};const writing=${JSON.stringify(writing)};const cssURL=${JSON.stringify(cssURL)};${esc.toString()}\n${defaults.toString()}\n${art.toString()}\n${template.toString()}\n${bare.toString()}\n${fs.readFileSync(path.join(out,'preview.js'),'utf8')}</script></body></html>`;
fs.writeFileSync(path.join(out,'potato-collection-preview.html'),page);
let readme='# Potato · Earth & Edge\n\nFifteen original designs for Minwoo & Phoenix: five threads, five device comms and five compact buds.\n\n[Open the editable preview](https://raw.githack.com/lexdoescodingnow/templates/main/potato/potato-collection-preview.html) · [Download the preview](https://github.com/lexdoescodingnow/templates/raw/refs/heads/main/potato/potato-collection-preview.html) · [Forum masterpost](../forum-posts/potato-forum-masterpost.txt) · [Complete download](potato-collection.zip)\n\nEach preview appears above its copyable code. The HTML preview can be downloaded and opened in a browser. On GitHub, use **Copy raw file** on the individual `.txt` snippets.\n\n';
for(const type of ['thread','comms','bud']){readme+=`## ${type==='thread'?'Threads':type==='comms'?'Comms':'Buds'}\n\n| Design | GIFs | Snippet |\n| --- | ---: | --- |\n`;for(const d of designs.filter(d=>d.type===type))readme+=`| ${d.number} · ${d.name} | ${d.images} | [${d.name}](${d.file}) |\n`;readme+='\n';}
readme+='## Editing\n\nNames, link URLs, titles, status, GIFs and paragraph text precede decoration and the single stylesheet link. The snippets and forum copy boxes retain Minwoo & Phoenix, the requested Tumblr GIFs and lorem ipsum. [Placeholder variants](potato-placeholder-masterpost.txt) retain literal `[url]`, `[name]` and `[text]` at the top; the editor has a dedicated copy button for them. No comments, hidden tips or editing notes appear inside posted HTML or CSS.\n\nInside `[dohtml]`, `<b>` / `<strong>`, `<i>` / `<em>`, and `<u>` carry the member gradients. The editor also accepts `[b]`, `[i]`, `[u]` and converts them into HTML when copying. Raw BBCode entered directly in a forum HTML block depends on that forum’s parser. Bold and underline run group 1 → 2 → 3; italics reverse the gradient.\n\nAll frames, heading accents and message borders inherit the forum variables `--mgrgb1`, `--mgrgb2`, `--mgrgb3`. Preview palettes are not copied into posting code. Neutral surfaces follow Blue Hour’s `html[color-mode="light"]` and `html[color-mode="dark"]`; an explicit mode takes precedence over the system preference.\n\nComms use plain `<p>` messages, including successive opening `<p>` tags without closing tags. Change `data-direction` between `received`, `sent`, and `alternating`. Device buttons are decorative. Buds are intended for replies of approximately 100 words or fewer, with no forced text clipping.\n\nClear a GIF field to remove its image or add a URL to include one. For hand edits, remove the image’s `pt1-shot` span; empty media containers collapse. Portrait crop positions are editable via `--pt-crop`, such as `50% 35%`. The image-free Russet Press, Chit Circuit, Wedgelet and Rootbound Kiss also accept images.\n\nThe preview embeds all layout CSS and the editor. GIFs load online. Forum snippets need no JavaScript; they load one import-free stylesheet, `potato-earth-and-edge-v1.css`, using local system fonts. Layouts use modern container queries, `:has()` and `color-mix()`.\n\n## Rebuilding\n\nRun `node potato/build.cjs`, then `python tools/build_forum_posts.py`, and `python potato/package.py`. `designs.json` supplies the public names. The Potato exception in `tools/forum_presentation.py` preserves the requested lorem ipsum in copyable code.\n';
fs.writeFileSync(path.join(out,'README.md'),readme);
console.log('Built 15 Potato designs, placeholder collection, editable preview, standalone CSS and guide.');
