const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const {JSDOM,VirtualConsole}=require('jsdom');
const csstree=require('css-tree');
const root=__dirname;
const designs=require('./designs.json');
const model=require('./cheese-model.js');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const css=read('cheese-fromagerie-v1.css');
const ast=csstree.parse(css,{parseCustomProperty:true,positions:true});
let rules=0;
csstree.walk(ast,{visit:'Rule',enter(n){rules++;assert(csstree.generate(n.prelude).includes('.bh-cheese'));}});
assert.equal(designs.length,15);
assert.equal(new Set(designs.map(d=>d.name)).size,15);
for(const type of ['thread','comms','bud'])assert.equal(designs.filter(d=>d.type===type).length,5);
assert(css.includes('html[color-mode="dark"]'));
assert(css.includes('html:not([color-mode="light"]):not([color-mode="dark"])'));
assert(css.includes('background-image:var(--ch-reverse)'));
assert(!css.includes('/*'));
assert(!/max-height|overflow:auto/.test(css));
const errors=[];
const vc=new VirtualConsole();
vc.on('jsdomError',e=>{if(e.type!=='css parsing'&&e.type!=='css-parsing')errors.push(e.message);});
let clipboard='',download;
const dom=new JSDOM(read('cheese-collection-preview.html'),{runScripts:'dangerously',virtualConsole:vc,beforeParse(w){w.scrollTo=()=>{};Object.defineProperty(w.navigator,'clipboard',{value:{writeText:async text=>{clipboard=text;}}});w.URL.createObjectURL=()=> 'blob:cheese-validation';w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=function(){download=this.download;};}});
const w=dom.window,doc=w.document,$=s=>doc.querySelector(s);
const set=(s,value)=>{$(s).value=value;$(s).dispatchEvent(new w.Event('input',{bubbles:true}));};
const change=(s,value)=>{$(s).value=value;$(s).dispatchEvent(new w.Event('change',{bubbles:true}));};
const choices=[...doc.querySelectorAll('.pv-choice')];
assert.equal(choices.length,15);
for(let i=0;i<15;i++){
 choices[i].click();
 const d=designs[i],code=read(model.cheeseFilename(d));
 assert.equal($('#pv-code').value,code);
 assert(code.startsWith('[dohtml]\n')&&code.endsWith('[/dohtml]\n'));
 assert(['[name]','[text]','[url]'].every(x=>code.slice(0,250).includes(x)));
 assert(!/<!--|\/\*|===/.test(code));
 assert(!/<script|<iframe/i.test(code));
 assert.equal((code.match(/<link /g)||[]).length,1);
 assert.equal($('#pv-stage .chs-name').textContent,'Minseo & Tommy');
 assert.equal(doc.querySelectorAll('#pv-stage .chs-media img').length,d.gifs);
 if(d.type==='bud')assert($('#pv-stage .chs-copy').textContent.split(/\s+/).length<=100);
 if(d.type==='comms')assert.equal(doc.querySelectorAll('#pv-stage .chs-copy > p').length,3);
 for(const tag of ['b','i','u'])assert($('#pv-stage .chs-copy '+tag));
 for(let n=0;n<d.gifs;n++)$('[data-remove="0"]').click();
 assert(!$('#pv-stage .chs-media'));
 assert(!$('#pv-code').value.includes('chs-media'));
 for(let n=0;n<3;n++)$('#pv-add-gif').click();
 assert.equal(doc.querySelectorAll('#pv-stage .chs-media img').length,3);
 $('#pv-reset').click();
 assert.equal($('#pv-code').value,code);
}
choices[0].click();
set('#pv-name','Minseo & Tommy <3');
set('#pv-title','A "bright" thing');
set('#pv-url','https://example.com/?a=1&b=2');
set('#pv-body','<p>[b]First[/b] <i>second</i><p>[u]Third[/u] <strong>fourth</strong><script>window.bad=1</script><a href="javascript:bad()" onclick="bad()">five</a>');
assert.equal(doc.querySelectorAll('#pv-stage .chs-copy > p').length,2);
assert.equal($('#pv-stage .chs-copy b').textContent,'First');
assert.equal($('#pv-stage .chs-copy u').textContent,'Third');
assert(!$('#pv-code').value.includes('<script>'));
assert(!$('#pv-code').value.includes('onclick'));
assert(!$('#pv-code').value.includes('javascript:'));
assert($('#pv-code').value.includes('Minseo &amp; Tommy &lt;3'));
assert($('#pv-code').value.includes('a=1&amp;b=2'));
assert.equal(w.bad,undefined);
choices[1].click();choices[0].click();
assert.equal($('#pv-name').value,'Minseo & Tommy <3');
set('#pv-body','First paragraph.\n\nSecond paragraph.');
assert.equal(doc.querySelectorAll('#pv-stage .chs-copy > p').length,2);
$('#pv-reset').click();choices[5].click();
set('#pv-flow','mixed');
assert.equal($('#pv-stage .chs-comms').dataset.flow,'mixed');
change('#pv-mode','dark');assert.equal(doc.documentElement.getAttribute('color-mode'),'dark');
change('#pv-mode','light');assert.equal(doc.documentElement.getAttribute('color-mode'),'light');
change('#pv-mode','system');assert(!doc.documentElement.hasAttribute('color-mode'));
const exported=$('#pv-code').value;
change('#pv-palette','ember');
assert.equal(doc.documentElement.style.getPropertyValue('--mgrgb1'),'187,101,65');
assert.equal($('#pv-code').value,exported);
change('#pv-width','320');assert.equal($('#pv-stage').style.width,'320px');
$('#pv-view-all').click();assert.equal(doc.querySelectorAll('#pv-gallery .bh-cheese').length,15);
$('[data-open="14"]').click();assert.equal($('#pv-design-title').textContent,'Last Shaving');
(async()=>{
 await $('#pv-copy').onclick();assert.equal(clipboard,$('#pv-code').value);
 $('#pv-download').click();assert.equal(download,'cheese-last-shaving-bud-05.txt');
 assert.deepEqual(errors,[]);
 console.log('PASS: '+rules+' scoped CSS rules; 15 snippets; all editor selections and default exports; 0/3/default image states; BBCode conversion; successive opening paragraphs; name and URL escaping; edit persistence; copy/download; mode, palette and width controls; gallery navigation.');
 console.log('No browser layout, image loading, or live forum verification is claimed.');
 w.close();
})().catch(e=>{console.error(e);process.exitCode=1;w.close();});
