const fs=require('node:fs');
const path=require('node:path');
const dir=__dirname;
const read=n=>fs.readFileSync(path.join(dir,n),'utf8');
const designs=JSON.parse(read('designs.json'));
const model=require('./sesame-model.js');
for(const d of designs)fs.writeFileSync(path.join(dir,model.sesameFilename(d)),model.sesameSnippet(d,model.sesameDefaults(d)));
const css=read('sesame-preview.css')+'\n'+read('sesame-atelier-v1.css');
const script=read('sesame-model.js')+'\nconst SESAME_DESIGNS = '+JSON.stringify(designs)+';\n'+read('sesame-editor.js');
const nav=['thread','comms','bud'].map(type=>'<div class="nav-group"><h2>'+({thread:'Threads',comms:'Comms',bud:'Buds'}[type])+'</h2>'+designs.filter(d=>d.type===type).map(d=>`<button type="button" data-design="${d.slug}" aria-pressed="false"><small>${d.number}</small><span>${d.name}</span></button>`).join('')+'</div>').join('');
fs.writeFileSync(path.join(dir,'sesame-collection-preview.html'),read('preview-shell.html').replace('SESAME_STYLES',()=>css).replace('SESAME_NAV',()=>nav).replace('SESAME_SCRIPT',()=>script));
console.log('Built 15 Sesame snippets and the standalone editor.');
