const fs=require('node:fs'),path=require('node:path');
const out=__dirname;
const cssURL='https://cdn.jsdelivr.net/gh/lexdoescodingnow/templates@main/cucumber/cucumber-cool-current-v1.css';
const gifs=['https://64.media.tumblr.com/4125c90392ec277c761b1d2427f4feb3/9ec4b4db231f7d93-2e/s400x600/70cfbcf3debacabcaf1bd9dc2b7917ec9eae073a.gifv','https://64.media.tumblr.com/4b4e61332ab9db142357da4fb0f2c1e8/9ec4b4db231f7d93-bb/s400x600/d9849a35430d61ff40b65fc315a27821340e6c59.gifv'];
const writing={thread:'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <b>“Aliquam erat volutpat.”</b> Pellentesque vel urna vitae libero blandit lacinia. Maecenas euismod, arcu vitae luctus vestibulum, nibh massa tempus felis, sed pretium sem mi nec augue.</p>\n<p>Donec vitae leo sit amet augue congue malesuada. <i>Nullam id nisi quis justo tincidunt interdum.</i> Sed suscipit, ipsum a volutpat elementum, ante neque luctus quam, at interdum turpis felis vitae metus. Integer non purus sed mi aliquam finibus.</p>\n<p>Curabitur id ligula ac augue sodales congue. <u>Praesent vel velit sed arcu.</u> Cras imperdiet lorem non augue posuere, eu eleifend justo finibus. Suspendisse potenti. Fusce euismod elit eget nibh interdum, sed egestas justo aliquet.</p>',comms:'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>\n<p><b>Aliquam erat volutpat.</b> Donec vitae leo sit amet augue.</p>\n<p><i>Nullam id nisi quis justo.</i> <u>Praesent vel velit.</u></p>',bud:'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <b>“Aliquam erat volutpat.”</b> Donec vitae leo sit amet augue congue malesuada. <i>Nullam id nisi quis justo</i> tincidunt interdum. <u>Praesent vel velit</u> sed arcu.</p>'};
const designs=[
['thread','Cutglass Current','cutglass-current',1,'cool to the touch','a moment held in glass',1],
['thread','Peel Continuum','peel-continuum',2,'a little closer still','in one unbroken line',2],
['thread','Hothouse Hours','hothouse-hours',2,'where the light lingers','beneath the climbing vines',3],
['thread','Rind & Reason','rind-and-reason',0,'beneath the surface','a quiet kind of clarity',4],
['thread','Cucumber Water','cucumber-water',2,'let the world slow down','still water / soft company',5],
['comms','Dewdial','dewdial',1,'Zhiyuan','online now',5],
['comms','Pithline','pithline',1,'Tao','secure connection',4],
['comms','Tendril Touch','tendril-touch',1,'Zhiyuan','tap into the moment',3],
['comms','Coolwire','coolwire',1,'Tao','direct messages',2],
['comms','Slice Signal','slice-signal',0,'Tao & Zhiyuan','new messages',1],
['bud','Sativus Speck','sativus-speck',1,'just a little moment','cucumber / a small beginning',1],
['bud','Dewprint','dewprint',0,'stay a second','a trace of something good',5],
['bud','Peellet','peellet',1,'softly unfolding','one small turn',2],
['bud','Crisp Interval','crisp-interval',2,'between you and me','a pause in the day',4],
['bud','Tendril Trace','tendril-trace',1,'a little room to grow','here, with you',3]
].map((a,i)=>({type:a[0],name:a[1],slug:a[2],images:a[3],sampleTitle:a[4],subtitle:a[5],motif:a[6],number:String(i%5+1).padStart(2,'0'),file:`cucumber-${a[2]}-${a[0]}-${String(i%5+1).padStart(2,'0')}.txt`}));
function esc(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');}
function defaults(d){return {name:'[name]',url:'[url]',title:'[text]',subtitle:d.subtitle,gif1:d.images?gifs[d.slug==='pithline'||d.slug==='coolwire'||d.slug==='tendril-trace'?1:0]:'',gif2:d.images>1?gifs[1]:'',crop1:d.slug==='peellet'?'50% 48%':'50% 35%',crop2:'50% 35%',copy:writing[d.type],time:'09:41',receipt:'Delivered',direction:'received'};}
function previewState(d,s){return {...s,name:s.name==='[name]'?'Tao & Zhiyuan':s.name,title:s.title==='[text]'?d.sampleTitle:s.title};}
function art(n){
const seeds='<path d="M49 48C38 35 43 26 48 27C53 30 54 39 49 48ZM43 54C26 60 20 52 24 48C30 45 39 49 43 54ZM54 55C66 43 75 48 73 53C71 59 61 60 54 55Z" fill="currentColor" opacity=".32"/>';
const slice='<circle cx="50" cy="50" r="43" fill="currentColor" fill-opacity=".04" stroke="currentColor" stroke-width="3"/><circle cx="50" cy="50" r="35" fill="none" stroke="currentColor" stroke-width=".8" stroke-dasharray="1 3"/>'+seeds;
if(n===2)return '<svg viewBox="0 0 180 70" aria-hidden="true"><path d="M4 41C30 0 55 9 54 34S85 80 102 41S139-4 176 27L169 41C137 9 121 31 111 55S56 76 47 46S29 26 13 50Z" fill="currentColor" fill-opacity=".1" stroke="currentColor" stroke-width="1.2"/><path d="M5 42C31 15 45 23 49 44S83 80 105 45S138 3 174 31" fill="none" stroke="currentColor" stroke-width="3"/></svg>';
if(n===3)return '<svg viewBox="0 0 100 140" aria-hidden="true"><path d="M42 134C28 110 65 88 55 64S20 30 52 8M53 90C82 107 94 69 76 67C60 65 63 82 72 80M43 35C19 39 9 17 18 14C27 10 31 23 24 23" fill="none" stroke="currentColor" stroke-width="1.5"/><path d="M51 70C28 74 22 55 25 46C44 46 56 52 51 70ZM44 110C42 88 65 85 74 91C69 106 57 113 44 110Z" fill="currentColor" fill-opacity=".08" stroke="currentColor"/><path d="M61 38C63 16 83 16 86 29L80 49C74 65 54 60 59 45Z" fill="currentColor" fill-opacity=".12" stroke="currentColor"/><path d="M66 46l9-19m-5 23l9-19" stroke="currentColor" stroke-width=".8"/></svg>';
if(n===4)return '<svg viewBox="0 0 160 65" aria-hidden="true"><path d="M14 42C7 26 24 10 51 15L131 25C153 29 151 51 134 53L41 57C25 56 16 50 14 42Z" fill="currentColor" fill-opacity=".06" stroke="currentColor" stroke-width="1.5"/><path d="M27 30Q51 21 128 33M24 38Q52 34 132 41M31 47Q52 44 123 47" fill="none" stroke="currentColor" stroke-width="1.2" stroke-dasharray="7 5"/><path d="M141 35l10-6" stroke="currentColor" stroke-width="2"/></svg>';
if(n===5)return '<svg viewBox="0 0 110 125" aria-hidden="true"><g transform="translate(27 32) scale(.7)">'+slice+'</g><path d="M22 10C18 20 7 27 10 37C13 49 32 47 34 36C36 28 26 21 22 10ZM77 4C74 11 68 15 69 20C71 29 84 27 85 21C86 15 79 9 77 4ZM21 88C18 93 13 98 14 103C16 109 25 109 28 104C30 99 24 93 21 88Z" fill="currentColor" fill-opacity=".06" stroke="currentColor" stroke-width="1.1"/></svg>';
return '<svg viewBox="0 0 100 100" aria-hidden="true">'+slice+'</svg>';
}
function template(d,s){
const media=[s.gif1,s.gif2].map((g,i)=>g?`<span class="cu-shot"><img src="${esc(g)}" alt="Character GIF ${i+1}" style="--cu-crop:${esc(s['crop'+(i+1)])}"></span>`:'').filter(Boolean).join('\n');
const chrome={dewdial:['DEWDIAL','▂ ▄ ▆','Message','↑'],pithline:['PITH / LINK','● LIVE','Compose','↵'],'tendril-touch':['TENDRIL','●','Reply','↑'],coolwire:['● ● ●','COOLWIRE','Write a message','↗'],'slice-signal':['SLICE / SIGNAL','▰','Swipe to reply','↑']}[d.slug];
return `[dohtml]\n<div class="cu1 cu1-${d.type} cu1-${d.slug}"${chrome?` data-direction="${esc(s.direction)}"`:''}>\n<div class="cu-layout">\n<div class="cu-head">\n<a class="cu-name" href="${esc(s.url)}">${esc(s.name)}</a>\n<span class="cu-title">${esc(s.title)}</span>\n<span class="cu-sub">${esc(s.subtitle)}</span>\n</div>\n${media?`<div class="cu-media">\n${media}\n</div>\n`:''}<div class="cu-copy">\n${s.copy}\n</div>\n${chrome?`<div class="cu-time">${esc(s.time)}</div>\n<div class="cu-receipt">${esc(s.receipt)}</div>\n`:''}<div class="cu-art" aria-hidden="true">${art(d.motif)}</div>\n<div class="cu-edition">cucumber / ${d.type==='bud'?'small moments':d.type==='comms'?'connected':'cool current'} ${d.number}</div>\n${chrome?`<div class="cu-chrome" aria-hidden="true"><span>${chrome[0]}</span><span>${chrome[1]}</span></div>\n<div class="cu-device" aria-hidden="true"><span>${chrome[2]}</span><span>${chrome[3]}</span></div>\n`:''}</div>\n</div>\n<link rel="stylesheet" href="${cssURL}">\n[/dohtml]`;
}
function bare(code){return code.replace(/\[\/?dohtml\]/gi,'').replace(/<link[^>]*>/gi,'');}
const css=fs.readFileSync(path.join(out,'layout.css'),'utf8');
fs.writeFileSync(path.join(out,'cucumber-cool-current-v1.css'),css);
fs.writeFileSync(path.join(out,'designs.json'),JSON.stringify(designs,null,2)+'\n');
for(const d of designs)fs.writeFileSync(path.join(out,d.file),template(d,defaults(d))+'\n');
const cards=designs.map(d=>{
const s=defaults(d),code=template(d,s);
const fields=[['name','[name] · Names'],['url','[url] · Link URL'],['title','[text] · '+(d.type==='comms'?'Contact':'Title')],['subtitle',d.type==='comms'?'Status':'Subtitle'],['gif1','GIF 1 URL'],['gif2','GIF 2 URL'],['crop1','GIF 1 position'],['crop2','GIF 2 position'],...(d.type==='comms'?[['time','Time'],['receipt','Receipt']]:[])].map(([key,label])=>`<label>${label}<input name="${key}" value="${esc(s[key])}" spellcheck="false"></label>`).join('');
return `<section class="cp-card" id="${d.slug}" data-kind="${d.type}"><header class="cp-card-head"><span>${d.type==='bud'?'BUDS':d.type.toUpperCase()} / ${d.number}</span><h2>${esc(d.name)}</h2><a href="#top" aria-label="Back to top">↑</a></header><div class="cp-stage">${bare(template(d,previewState(d,s)))}</div><details class="cp-editor"><summary>Edit this template</summary><form>${fields}${d.type==='comms'?'<label>Message direction<select name="direction"><option value="received">Received</option><option value="sent">Sent</option><option value="alternating">Alternating</option></select></label>':''}<label class="cp-writing">${d.type==='comms'?'Messages':'Writing'}<textarea name="copy" rows="7" spellcheck="false">${esc(s.copy)}</textarea></label><button class="cp-reset" type="button">Reset sample</button></form></details><div class="cp-actions"><button class="cp-copy" type="button">Copy template</button><button class="cp-named" type="button">Copy for Tao &amp; Zhiyuan</button><a href="${d.file}">Posting snippet ↗</a><span class="cp-status" role="status"></span></div><textarea class="cp-code" aria-label="${esc(d.name)} posting code" readonly spellcheck="false">${esc(code)}</textarea></section>`;
}).join('\n');
const page=`<!doctype html>\n<html lang="en" color-mode="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cucumber · Tao &amp; Zhiyuan</title><style>${css}\n${fs.readFileSync(path.join(out,'preview.css'),'utf8')}</style></head><body><main class="cp-main" id="top"><header class="cp-intro"><div class="cp-collection"><span>TAO / ZHIYUAN</span><span>CUCUMBER / FIFTEEN DESIGNS</span></div><div class="cp-masthead"><div><span class="cp-kicker">THE CUCUMBER COLLECTION</span><h1>Cool<br><em>current.</em></h1></div><span class="cp-emblem">${art(5)}</span></div><nav class="cp-toplinks"><a href="../forum-posts/cucumber-forum-masterpost.txt">Forum masterpost ↗</a><a href="cucumber-collection.zip">Download collection ↗</a><a href="README.md">Editing guide ↗</a></nav></header><nav class="cp-controls" aria-label="Preview controls"><div class="cp-filters"><button data-filter="all" aria-pressed="true">All 15</button><button data-filter="thread" aria-pressed="false">Threads</button><button data-filter="comms" aria-pressed="false">Comms</button><button data-filter="bud" aria-pressed="false">Buds</button></div><label>Appearance<select id="cp-mode"><option value="light">Light</option><option value="dark">Dark</option><option value="system">System</option></select></label><label>Width<select id="cp-width"><option value="full">Full</option><option value="390">390px</option><option value="320">320px</option><option value="260">260px</option></select></label><label>Member palette<select id="cp-palette"><option value="plum">Plum / jade</option><option value="blue">Blue / lilac</option><option value="copper">Copper / teal</option></select></label></nav>${cards}<footer class="cp-footer">CUCUMBER / COOL CURRENT <a href="#top">Back to top ↑</a></footer></main><script>const designs=${JSON.stringify(designs)};const gifs=${JSON.stringify(gifs)};const writing=${JSON.stringify(writing)};const cssURL=${JSON.stringify(cssURL)};${esc.toString()}\n${defaults.toString()}\n${previewState.toString()}\n${art.toString()}\n${template.toString()}\n${bare.toString()}\n${fs.readFileSync(path.join(out,'preview.js'),'utf8')}</script></body></html>`;
fs.writeFileSync(path.join(out,'cucumber-collection-preview.html'),page);
console.log('Built 15 Cucumber designs, editable preview and standalone CSS.');
