const fs=require('node:fs');
const path=require('node:path');
const root=__dirname;
const designs=require('./designs.json');
const {gingerDefaults,gingerFilename,gingerSnippet,gingerMarkup}=require('./ginger-model.js');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
for(const d of designs)fs.writeFileSync(path.join(root,gingerFilename(d)),gingerSnippet(d,gingerDefaults(d)));
const preview=`<!doctype html>
<html lang="en" color-mode="light">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Ginger · Fifteen JCink Templates</title><meta name="description" content="Five threads, five comms and five buds. Preview, edit and copy the Ginger collection."><style>${read('ginger-apothecary-v1.css')}</style><style>${read('ginger-preview.css')}</style></head>
<body>
<header class="pv-top"><h1 class="pv-brand">Ginger</h1><div class="pv-sub">SOME CONNECTIONS STAY<br>05 THREADS · 05 COMMS · 05 BUDS</div><div class="pv-toolbar"><label>Mode <select id="pv-mode"><option value="light">Light</option><option value="dark">Dark</option><option value="system">System</option></select></label><label>Members <select id="pv-palette"><option value="poster">Poster</option><option value="lagoon">Lagoon</option><option value="ember">Ember</option><option value="mono">Monochrome</option><option value="custom">Custom</option></select></label><div class="pv-colours"><input id="pv-colour-1" aria-label="Member colour 1" type="color" value="#9b6858"><input id="pv-colour-2" aria-label="Member colour 2" type="color" value="#8e7286"><input id="pv-colour-3" aria-label="Member colour 3" type="color" value="#637c70"></div><label>Width <select id="pv-width"><option value="full">Full</option><option value="375">375 px</option><option value="320">320 px</option></select></label><button id="pv-view-all" aria-pressed="false">View all 15</button></div></header>
<main><div class="pv-workspace" id="pv-workspace"><nav class="pv-nav" id="pv-nav" aria-label="Ginger designs"></nav><section class="pv-canvas" aria-label="Template preview"><div class="pv-caption"><div><h2 id="pv-design-title">Rhizome Reverie</h2><p id="pv-design-description"></p></div><div class="pv-stepper"><button id="pv-previous" aria-label="Previous design">‹</button><button id="pv-next" aria-label="Next design">›</button></div></div><div class="pv-stage" id="pv-stage">${gingerMarkup(designs[0],{...gingerDefaults(designs[0]),name:'Aaron & Bandy',title:designs[0].sample,url:'#'})}</div></section><aside class="pv-editor" id="pv-editor"><h2>Edit & copy</h2><label class="pv-field">Name<input id="pv-name" value="[name]"></label><label class="pv-field"><span id="pv-title-label">Title</span><input id="pv-title" value="[text]"></label><label class="pv-field">Name link<input id="pv-url" value="[url]"></label><div class="pv-two" id="pv-device-fields" hidden><label class="pv-field">Time<input id="pv-time" value="19:08"></label><label class="pv-field">Messages<select id="pv-flow"><option value="received">Received</option><option value="sent">Sent</option><option value="mixed">Alternating</option></select></label></div><div id="pv-gifs"></div><button class="pv-add" id="pv-add-gif">Add GIF</button><label class="pv-field"><span class="pv-writing-label">Writing<span id="pv-word-count" class="pv-count"></span></span><textarea id="pv-body" spellcheck="false"></textarea></label><p class="pv-hint">Use ordinary &lt;p&gt; paragraphs. [b], [i] and [u] are converted to HTML when copied. Preview colours and mode stay outside your posting code.</p><div class="pv-actions"><button id="pv-copy" class="pv-primary">Copy JCink code</button><button id="pv-download">Download .txt</button></div><p class="pv-status" id="pv-status" role="status" aria-live="polite"></p><details id="pv-code-details"><summary>View posting code</summary><textarea class="pv-code" id="pv-code" readonly aria-label="JCink posting code" spellcheck="false"></textarea></details><button id="pv-reset" class="pv-reset">Reset this design</button><p class="pv-hint">Edits remain while this page is open. Download an edited snippet to keep it.</p></aside></div><section id="pv-gallery" class="pv-gallery" aria-label="All fifteen Ginger designs" hidden></section></main>
<footer class="pv-footer"><span>Ginger · Some Connections Stay</span><a href="https://github.com/lexdoescodingnow/templates/tree/main/ginger">GitHub collection</a><span>Member colours · Blue Hour light/dark · Ready for [dohtml]</span></footer>
<script type="application/json" id="ginger-designs">${JSON.stringify(designs).replace(/</g,'\\u003c')}</script><script>${read('ginger-model.js')}</script><script>${read('ginger-editor.js')}</script>
</body></html>`;
fs.writeFileSync(path.join(root,'ginger-collection-preview.html'),preview);
console.log(`Built ${designs.length} posting snippets and the standalone preview.`);

