const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const {JSDOM,VirtualConsole}=require('jsdom');
const cssTree=require('css-tree');
const root=__dirname;
const designs=require('./designs.json');
const model=require('./cocktail-model.js');
const source=fs.readFileSync(path.join(root,'cocktail-afterhours-v1.css'),'utf8');
const ast=cssTree.parse(source,{parseCustomProperty:true,positions:true});
let rules=0;
cssTree.walk(ast,{visit:'Rule',enter(node){rules++; const sel=cssTree.generate(node.prelude);assert(sel.includes('.bh-cocktail'),sel);}});
const consoleErrors=[];
const virtualConsole=new VirtualConsole();
virtualConsole.on('jsdomError',e=>{if(e.type!=='css parsing')consoleErrors.push(e.message);});
let clipboard='';
let download;
const dom=new JSDOM(fs.readFileSync(path.join(root,'cocktail-collection-preview.html'),'utf8'),{runScripts:'dangerously',virtualConsole,beforeParse(w){w.scrollTo=()=>{};Object.defineProperty(w.navigator,'clipboard',{value:{writeText:async value=>{clipboard=value;}}});w.URL.createObjectURL=()=> 'blob:cocktail-test';w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=function(){download={name:this.download,url:this.href};};}});
const w=dom.window,doc=w.document;
const $=sel=>doc.querySelector(sel);
const set=(sel,value)=>{$(sel).value=value;$(sel).dispatchEvent(new w.Event('input',{bubbles:true}));};
const click=sel=>$(sel).click();
const change=(sel,value)=>{$(sel).value=value;$(sel).dispatchEvent(new w.Event('change',{bubbles:true}));};
const choices=[...doc.querySelectorAll('.pv-choice')];
assert.equal(choices.length,15);
for(let i=0;i<15;i++){
 choices[i].click();
 const d=designs[i];
 assert.equal($('#pv-design-title').textContent,d.name);
 assert.equal($('#pv-code').value,fs.readFileSync(path.join(root,model.cocktailFilename(d)),'utf8'));
 assert.equal(doc.querySelectorAll('#pv-stage .ckt-media img').length,d.gifs);
 assert.equal($('#pv-stage .ckt-name').textContent,'Callum & Dae');
 for(let n=0;n<d.gifs;n++)click('[data-remove="0"]');
 assert.equal(doc.querySelectorAll('#pv-stage .ckt-media').length,0);
 assert(!$('#pv-code').value.includes('class="ckt-media"'));
 for(let n=0;n<3;n++)click('#pv-add-gif');
 assert.equal(doc.querySelectorAll('#pv-stage .ckt-media img').length,3);
 click('#pv-reset');
 assert.equal($('#pv-code').value,model.cocktailSnippet(d,model.cocktailDefaults(d)));
}
choices[0].click();
set('#pv-name','Callum & Dae <3');
set('#pv-title','A "last" drink');
set('#pv-url','https://example.com/?a=1&b=2');
set('#pv-body','<p>[b]One[/b] <i>two</i><p>[u]Three[/u] <em>four</em><script>window.bad=1</script><a href="javascript:bad()" onclick="bad()">five</a>');
assert.equal(doc.querySelectorAll('#pv-stage .ckt-copy > p').length,2);
assert.equal($('#pv-stage .ckt-copy b').textContent,'One');
assert.equal($('#pv-stage .ckt-copy u').textContent,'Three');
assert(!$('#pv-code').value.includes('<script>'));
assert(!$('#pv-code').value.includes('onclick'));
assert(!$('#pv-code').value.includes('javascript:'));
assert($('#pv-code').value.includes('Callum &amp; Dae &lt;3'));
assert($('#pv-code').value.includes('a=1&amp;b=2'));
assert.equal(w.bad,undefined);
choices[1].click();choices[0].click();
assert.equal($('#pv-name').value,'Callum & Dae <3');
set('#pv-body','One paragraph.\n\nAnother paragraph.');
assert.equal(doc.querySelectorAll('#pv-stage .ckt-copy > p').length,2);
click('#pv-reset');
choices[5].click();
change('#pv-flow','mixed');
$('#pv-flow').dispatchEvent(new w.Event('input',{bubbles:true}));
assert.equal($('#pv-stage .ckt-comms').dataset.flow,'mixed');
change('#pv-mode','dark');assert.equal(doc.documentElement.getAttribute('color-mode'),'dark');
change('#pv-mode','light');assert.equal(doc.documentElement.getAttribute('color-mode'),'light');
change('#pv-mode','system');assert(!doc.documentElement.hasAttribute('color-mode'));
const exported=$('#pv-code').value;
change('#pv-palette','ember');assert.equal(doc.documentElement.style.getPropertyValue('--mgrgb1'),'187,101,65');
assert.equal($('#pv-code').value,exported);
click('#pv-view-all');assert.equal(doc.querySelectorAll('#pv-gallery .bh-cocktail').length,15);
assert.equal($('#pv-workspace').hidden,true);
click('[data-open="14"]');assert.equal($('#pv-workspace').hidden,false);assert.equal($('#pv-design-title').textContent,'Nightcap');
(async()=>{
 await $('#pv-copy').onclick();
 assert.equal(clipboard,$('#pv-code').value);
 click('#pv-download');assert.equal(download.name,'cocktail-nightcap-bud-05.txt');
 assert.equal(download.url,'blob:cocktail-test');
 assert.deepEqual(consoleErrors,[]);
 console.log(`PASS: ${rules} scoped CSS rules parsed; 15 default export comparisons; add/remove/reset GIFs on all designs; edit persistence; BBCode conversion; open-p parsing; safe text and URL handling; message direction; mode and palette controls; gallery selection; copy and download code paths.`);
 console.log('DOM tests do not verify rendered layout or the forum/CDN integration.');
 w.close();
})().catch(e=>{console.error(e);process.exitCode=1;w.close();});
