const fs=require('fs'),path=require('path');
const root=__dirname,{designs,motif,initial,markup}=require('./passionfruit-model.cjs');
const revisionFile=path.join(root,'stylesheet-revision.txt');
const revision=process.env.PASSIONFRUIT_CSS_REVISION||(fs.existsSync(revisionFile)?fs.readFileSync(revisionFile,'utf8').trim():'main');
const cssUrl=`https://cdn.jsdelivr.net/gh/lexdoescodingnow/templates@${revision}/passionfruit/passionfruit-collection-v1.css`;
let css=fs.readFileSync(path.join(root,'passionfruit-source.css'),'utf8');
for(const m of ['flower','seed','section','filament']){
  const svg=motif(m).replace('<svg ','<svg xmlns="http://www.w3.org/2000/svg" ').replace('currentColor','black');
  css+='\n'+designs.filter(d=>d.motif===m).map(d=>`.pfr-${d.slug}`).join(',')+`{--pf-art:url("data:image/svg+xml,${encodeURIComponent(svg).replace(/'/g,'%27')}")}\n`;
}
fs.writeFileSync(path.join(root,'passionfruit-collection-v1.css'),css);
for(const d of designs)fs.writeFileSync(path.join(root,`passionfruit-${d.slug}-${d.type}-${d.number}.txt`),'[dohtml]\n'+markup(d,initial(d))+'\n\n<link rel="stylesheet" href="'+cssUrl+'">\n[/dohtml]\n');
fs.writeFileSync(path.join(root,'designs.json'),JSON.stringify(designs,null,2)+'\n');
const previewCss=fs.readFileSync(path.join(root,'passionfruit-preview.css'),'utf8');
const model=fs.readFileSync(path.join(root,'passionfruit-model.cjs'),'utf8');
const editor=fs.readFileSync(path.join(root,'passionfruit-editor.js'),'utf8');
const scriptValue=s=>JSON.stringify(s).replace(/</g,'\\u003c');
const html=`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Passionfruit · 15 JCink templates</title><style>${css.split('\n')[0]}\n${previewCss}</style></head>
<body><header><div><div class="overline">The Passionfruit collection</div><h1>Sweetness with a pulse.</h1><p>Fifteen templates for things said softly, late-night messages, and the moments in between. Inspired by Adriel & Lewis.</p></div><div class="flower" aria-hidden="true">${motif('flower')}</div></header>
<div class="toolbar"><label>Mode <select id="mode"><option value="light">Light</option><option value="dark">Dark</option><option value="system">System</option></select></label><label>Member colours <select id="palette"><option value="poster">Passionfruit</option><option value="ocean">Ocean</option><option value="rose">Rose</option><option value="forest">Forest</option><option value="mono">Monochrome</option></select></label><input id="colour1" type="color" value="#954477" aria-label="Member colour 1"><input id="colour2" type="color" value="#b36941" aria-label="Member colour 2"><input id="colour3" type="color" value="#735ea3" aria-label="Member colour 3"><label>Post width <select id="width"><option value="570">Forum</option><option value="375">375 px</option><option value="320">320 px</option></select></label><span class="space"></span><button id="all" aria-pressed="false">View all 15 designs</button></div>
<main class="layout" id="layout"><nav id="designs" aria-label="Template designs"></nav><section class="preview-area"><div class="title-row"><div><h2 id="designName"></h2><p id="designType"></p></div><div class="arrows"><button id="previous" aria-label="Previous design">←</button><button id="next" aria-label="Next design">→</button></div></div><p class="design-description" id="description"></p><div class="stage-shell" id="stageShell"><iframe id="stage" title="Selected template preview" sandbox="allow-same-origin"></iframe></div></section>
<aside class="editor"><h2>Make it yours</h2><label class="field"><span>Linked URL</span><input id="url" type="text"></label><label class="field"><span>Name</span><input id="name" type="text"></label><label class="field"><span>Title / status</span><input id="title" type="text"></label><label class="field" id="timeField"><span>Time</span><input id="time" type="text"></label><label class="field" id="directionField"><span>Message direction</span><select id="direction"><option value="received">Received</option><option value="sent">Sent</option><option value="mixed">Alternating</option></select></label><div class="field"><span>Character GIFs</span><div id="images"></div><button class="small" id="addGif">Add GIF</button></div><label class="field"><span>Writing / messages</span><textarea id="body" spellcheck="false"></textarea></label><div class="actions"><button id="copy">Copy code</button><button id="download">Download .txt</button><button id="reset">Reset design</button></div><div id="status" class="status" role="status"></div><details id="source"><summary>Posting code</summary><textarea id="code" readonly spellcheck="false" aria-label="Complete JCink posting code"></textarea></details><p class="notice">Use ordinary &lt;p&gt; paragraphs. [b], [i] and [u] are converted to HTML for posting. Untouched name, link and title fields remain placeholders in the copied code. Palette and mode controls affect the preview; the forum supplies them in posts. Edits stay here while this page is open—download to keep them.</p></aside></main><section class="gallery" id="gallery" aria-label="All 15 designs" hidden></section>
<footer>Passionfruit · five threads / five comms / five buds · <a href="https://github.com/lexdoescodingnow/templates/tree/main/passionfruit">View the collection on GitHub</a></footer>
<script>const CSS_URL=${scriptValue(cssUrl)};const TEMPLATE_CSS=${scriptValue(css)};\n${model}\n${editor}</script></body></html>`;
fs.writeFileSync(path.join(root,'passionfruit-collection-preview.html'),html);
console.log(`Built ${designs.length} snippets, shared CSS, design index and standalone preview.`);
