const fs=require('node:fs');
const path=require('node:path');
const out=__dirname;
const cssURL='https://cdn.jsdelivr.net/gh/lexdoescodingnow/templates@main/strawberry/strawberry-field-notes-v2.css';
const gifs=['https://64.media.tumblr.com/cca6dd1da20b54242db55e1df7f9cd3f/cbf6aa578e65d492-e0/s400x600/e7b1ffed3ef20378b4f49a71173d317f23c870b9.gifv','https://64.media.tumblr.com/4e917a77ac5fabc03cf1717d252b6f75/cbf6aa578e65d492-25/s400x600/d5e3503d4b92cb680cab8d0ee1a4a9f24dfac25c.gifv'];
const writing={
thread:'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <b>“Aliquam erat volutpat.”</b> Pellentesque vel urna vitae libero blandit lacinia. Maecenas euismod, arcu vitae luctus vestibulum, nibh massa tempus felis, sed pretium sem mi nec augue.</p>\n<p>Donec vitae leo sit amet augue congue malesuada. <i>Nullam id nisi quis justo tincidunt interdum.</i> Sed suscipit, ipsum a volutpat elementum, ante neque luctus quam, at interdum turpis felis vitae metus. Integer non purus sed mi aliquam finibus.</p>\n<p>Curabitur id ligula ac augue sodales congue. <u>Praesent vel velit sed arcu.</u> Cras imperdiet lorem non augue posuere, eu eleifend justo finibus. Suspendisse potenti. Fusce euismod elit eget nibh interdum, sed egestas justo aliquet.</p>',
comms:'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>\n<p><b>Aliquam erat volutpat.</b> Donec vitae leo sit amet augue.</p>\n<p><i>Nullam id nisi quis justo.</i> <u>Praesent vel velit.</u></p>',
bud:'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <b>“Aliquam erat volutpat.”</b> Donec vitae leo sit amet augue congue malesuada. <i>Nullam id nisi quis justo</i> tincidunt interdum. <u>Praesent vel velit</u> sed arcu.</p>'};
const designs=[
['thread','Achene Archive','achene-archive',1,'a record of the season','field notes / entry one',1],
['thread','Runner Index','runner-index',2,'where the paths divide','collected along the way',2],
['thread','Punnet Proof','punnet-proof',2,'a small inventory','strawberry / selected moments',3],
['thread','Calyx Cut','calyx-cut',1,'between the lines','an unfinished conversation',4],
['thread','Vesca Folio','vesca-folio',0,'the shape of a season','pages from the field',5],
['comms','Seedwave','seedwave',1,'Jinseok','online now',1],
['comms','Runner Relay','runner-relay',1,'Jaehoon','private conversation',2],
['comms','Punnet Pager','punnet-pager',0,'Jinseok','inbox / 03 messages',3],
['comms','Calyx Console','calyx-console',1,'Jaehoon','direct messages',4],
['comms','Fragaria Flip','fragaria-flip',2,'Jaehoon / Jinseok','message received',5],
['bud','Achene Note','achene-note',1,'a passing thought','in the margin',1],
['bud','Sepal Slip','sepal-slip',0,'a brief interlude','one small detail',4],
['bud','Fieldlet','fieldlet',2,'on another day','notes from the field',3],
['bud','Vesca Margin','vesca-margin',1,'a quiet footnote','left on the page',5],
['bud','Runner Mark','runner-mark',0,'a line in passing','the next entry',2]
].map((d,i)=>({type:d[0],name:d[1],slug:d[2],images:d[3],sampleTitle:d[4],subtitle:d[5],motif:d[6],number:String(i%5+1).padStart(2,'0'),file:`strawberry-${d[2]}-${d[0]}-${String(i%5+1).padStart(2,'0')}.txt`}));
function esc(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');}
function defaults(d){return {name:'[name]',url:'[url]',title:'[text]',subtitle:d.subtitle,gif1:d.images?gifs[d.slug==='runner-relay'||d.slug==='vesca-margin'?1:0]:'',gif2:d.images>1?gifs[1]:'',crop1:d.slug==='runner-relay'||d.slug==='vesca-margin'?'50% 30%':'78% 30%',crop2:'50% 30%',copy:writing[d.type],time:'14:08',receipt:'Delivered',direction:'received'};}
function previewState(d,s){return {...s,name:s.name==='[name]'?'Jaehoon & Jinseok':s.name,title:s.title==='[text]'?d.sampleTitle:s.title};}
function art(n){
const berry='<path d="M26 33C8 40 17 65 48 89C72 80 93 48 74 35C65 29 60 34 51 35C42 29 34 28 26 33Z" fill="currentColor" fill-opacity=".07" stroke="currentColor" stroke-width="1.5"/><path d="M51 34L35 24L42 39L27 38L43 47L51 35L60 47L62 35L75 32L60 29L65 18L53 27L50 14L47 29" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linejoin="round"/><path d="M31 49l1 3m15 3l1 3m19-10l-1 3M37 63l1 3m19-4l-1 3M47 75l1 3m23-17l-1 3" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/>';
if(n===2)return '<svg viewBox="0 0 130 70" aria-hidden="true"><path d="M5 53C27 56 30 22 53 25S87 54 123 20" fill="none" stroke="currentColor" stroke-width="1.5"/><path d="M31 40C12 42 15 19 16 15C30 21 36 27 31 40ZM52 24C42 8 65 5 70 8C65 19 60 24 52 24ZM94 37C95 56 114 52 120 47C111 38 104 32 94 37Z" fill="currentColor" fill-opacity=".08" stroke="currentColor"/><circle cx="53" cy="25" r="3" fill="currentColor"/><circle cx="94" cy="37" r="3" fill="currentColor"/></svg>';
if(n===3)return '<svg viewBox="0 0 100 100" aria-hidden="true"><path d="M18 46L25 85H77L85 46ZM23 58H81M25 70H78M34 48L38 84M51 48V84M70 48L66 84" fill="none" stroke="currentColor" stroke-width="1.5"/><g transform="translate(18 2) scale(.52)">'+berry+'</g><path d="M14 45H89" stroke="currentColor" stroke-width="3"/></svg>';
if(n===4)return '<svg viewBox="0 0 100 100" aria-hidden="true"><path d="M49 47C17 36 27 5 45 20C56-1 78 18 63 39C90 28 98 53 75 61C91 80 65 94 53 72C47 97 19 83 29 65C2 66 5 36 31 45Z" fill="currentColor" fill-opacity=".04" stroke="currentColor" stroke-width="1.2"/><circle cx="50" cy="52" r="10" fill="none" stroke="currentColor"/><path d="M50 43v18m-9-9h18m-15-6l12 12m0-12L44 58" stroke="currentColor" stroke-width=".8"/></svg>';
if(n===5)return '<svg viewBox="0 0 100 145" aria-hidden="true"><path d="M40 133Q44 90 49 38M46 77Q65 50 79 42M46 95Q23 84 18 61" fill="none" stroke="currentColor" stroke-width="1.5"/><path d="M50 55C21 54 21 27 23 16C46 22 52 36 50 55ZM48 67C45 40 73 33 87 34C84 54 72 67 48 67Z" fill="currentColor" fill-opacity=".06" stroke="currentColor"/><g transform="translate(-5 60) scale(.6)">'+berry+'</g></svg>';
return '<svg viewBox="0 0 100 100" aria-hidden="true">'+berry+'</svg>';
}
function template(d,s){
const media=[s.gif1,s.gif2].map((g,i)=>g?`<span class="sb-shot"><img src="${esc(g)}" alt="Character GIF ${i+1}" style="--sb-crop:${esc(s['crop'+(i+1)])}"></span>`:'').filter(Boolean).join('\n');
const device={seedwave:['SEEDWAVE','● ▰','Message…','↑'],'runner-relay':['RUNNER / RELAY','CONNECTED','Reply…','↗'],'punnet-pager':['PUNNET / PAGER','▂ ▄ ▆','◀','▶'],'calyx-console':['● ● ●','CALYX / MESSAGES','Write a message…','↵'],'fragaria-flip':['FRAGARIA','▂ ▄ ▆','MENU','REPLY']}[d.slug];
return `[dohtml]\n<div class="sb1 sb1-${d.type} sb1-${d.slug}"${device?` data-direction="${esc(s.direction)}"`:''}>\n<div class="sb-layout">\n<div class="sb-head">\n<a class="sb-name" href="${esc(s.url)}">${esc(s.name)}</a>\n<span class="sb-title">${esc(s.title)}</span>\n<span class="sb-sub">${esc(s.subtitle)}</span>\n</div>\n${media?`<div class="sb-media">\n${media}\n</div>\n`:''}<div class="sb-copy">\n${s.copy}\n</div>\n${device?`<div class="sb-receipt"><span>${esc(s.time)}</span><span>${esc(s.receipt)}</span></div>\n`:''}<div class="sb-art" aria-hidden="true">${art(d.motif)}</div>\n<div class="sb-edition">strawberry / ${d.type==='bud'?'field note':d.type==='comms'?'connected':'field notes'} ${d.number}</div>\n${device?`<div class="sb-chrome" aria-hidden="true"><span>${device[0]}</span><span>${device[1]}</span></div>\n<div class="sb-device" aria-hidden="true"><span>${device[2]}</span><span>${device[3]}</span></div>\n`:''}</div>\n</div>\n<link rel="stylesheet" href="${cssURL}">\n[/dohtml]`;
}
function bare(code){return code.replace(/\[\/?dohtml\]/gi,'').replace(/<link[^>]*>/gi,'');}
const css=fs.readFileSync(path.join(out,'layout.css'),'utf8');
fs.writeFileSync(path.join(out,'strawberry-field-notes-v2.css'),css);
fs.writeFileSync(path.join(out,'designs.json'),JSON.stringify(designs,null,2)+'\n');
for(const d of designs)fs.writeFileSync(path.join(out,d.file),template(d,defaults(d))+'\n');
const cards=designs.map(d=>{
const s=defaults(d),code=template(d,s);
const fields=[['name','Names'],['url','Link URL'],['title',d.type==='comms'?'Contact / conversation':'Title'],['subtitle',d.type==='comms'?'Status':'Subtitle'],['gif1','GIF 1 URL'],['gif2','GIF 2 URL'],['crop1','GIF 1 position'],['crop2','GIF 2 position'],...(d.type==='comms'?[['time','Time'],['receipt','Receipt']]:[])].map(([key,label])=>`<label>${label}<input name="${key}" value="${esc(s[key])}" spellcheck="false"></label>`).join('');
return `<section class="sf-card" id="${d.slug}" data-kind="${d.type}"><header class="sf-card-head"><span>${d.type==='bud'?'BUDS':d.type.toUpperCase()} / ${d.number}</span><h2>${esc(d.name)}</h2><a href="#top" aria-label="Back to top">↑</a></header><div class="sf-stage">${bare(template(d,previewState(d,s)))}</div><details class="sf-editor"><summary>Edit this template</summary><form>${fields}${d.type==='comms'?'<label>Message direction<select name="direction"><option value="received">Received</option><option value="sent">Sent</option><option value="alternating">Alternating</option></select></label>':''}<label class="sf-writing">${d.type==='comms'?'Messages':'Writing'}<textarea name="copy" rows="7" spellcheck="false">${esc(s.copy)}</textarea></label><button class="sf-reset" type="button">Reset sample</button></form></details><div class="sf-actions"><button class="sf-copy" type="button">Copy template</button><button class="sf-named" type="button">Copy with sample names</button><a href="${d.file}">GitHub snippet ↗</a><span class="sf-status" role="status"></span></div><textarea class="sf-code" aria-label="${esc(d.name)} posting code" readonly spellcheck="false">${esc(code)}</textarea></section>`;
}).join('\n');
const page=`<!doctype html>\n<html lang="en" color-mode="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Strawberry · Jaehoon &amp; Jinseok</title><style>${css}\n${fs.readFileSync(path.join(out,'preview.css'),'utf8')}</style></head><body><main class="sf-main" id="top"><header class="sf-intro"><div class="sf-collection"><span>JAEHOON / JINSEOK</span><span>FIELD NOTES / 15 DESIGNS</span></div><div class="sf-masthead"><div><span class="sf-kicker">THE STRAWBERRY COLLECTION</span><h1>Field<br><em>notes.</em></h1></div><span class="sf-emblem">${art(5)}</span></div><nav class="sf-toplinks"><a href="../forum-posts/strawberry-forum-masterpost.txt">Forum masterpost ↗</a><a href="strawberry-collection.zip">Download collection ↗</a><a href="README.md">Editing guide ↗</a></nav></header><nav class="sf-controls" aria-label="Preview controls"><div class="sf-filters"><button data-filter="all" aria-pressed="true">All 15</button><button data-filter="thread" aria-pressed="false">Threads</button><button data-filter="comms" aria-pressed="false">Comms</button><button data-filter="bud" aria-pressed="false">Buds</button></div><label>Appearance<select id="sf-mode"><option value="light">Light</option><option value="dark">Dark</option><option value="system">System</option></select></label><label>Width<select id="sf-width"><option value="full">Full</option><option value="390">390px</option><option value="320">320px</option><option value="260">260px</option></select></label><label>Member palette<select id="sf-palette"><option value="plum">Plum / jade</option><option value="blue">Blue / lilac</option><option value="copper">Copper / teal</option></select></label></nav>${cards}<footer class="sf-footer">STRAWBERRY / FIELD NOTES <a href="#top">Back to top ↑</a></footer></main><script>const designs=${JSON.stringify(designs)};const gifs=${JSON.stringify(gifs)};const writing=${JSON.stringify(writing)};const cssURL=${JSON.stringify(cssURL)};${esc.toString()}\n${defaults.toString()}\n${previewState.toString()}\n${art.toString()}\n${template.toString()}\n${bare.toString()}\n${fs.readFileSync(path.join(out,'preview.js'),'utf8')}</script></body></html>`;
fs.writeFileSync(path.join(out,'strawberry-collection-preview.html'),page);
console.log('Built 15 Strawberry designs, editable preview and standalone CSS.');
