const fs=require('node:fs');
const path=require('node:path');
const dir=__dirname;
const read=n=>fs.readFileSync(path.join(dir,n),'utf8');
const designs=JSON.parse(read('designs.json'));
const model=require('./mango-model.js');
for(const d of designs)fs.writeFileSync(path.join(dir,model.mangoFilename(d)),model.mangoSnippet(d,model.mangoDefaults(d)));
const css=read('mango-preview.css')+'\n'+read('mango-orchard-v1.css');
const script=read('mango-model.js')+'\nconst MANGO_DESIGNS = '+JSON.stringify(designs)+';\n'+read('mango-editor.js');
const nav=['thread','comms','bud'].map(type=>'<div class="nav-group"><h2>'+({thread:'Threads',comms:'Comms',bud:'Buds'}[type])+'</h2>'+designs.filter(d=>d.type===type).map(d=>`<button type="button" data-design="${d.slug}" aria-pressed="false"><small>${d.number}</small><span>${d.name}</span></button>`).join('')+'</div>').join('');
fs.writeFileSync(path.join(dir,'mango-collection-preview.html'),read('preview-shell.html').replace('MANGO_STYLES',()=>css).replace('MANGO_NAV',()=>nav).replace('MANGO_SCRIPT',()=>script));
console.log('Built 15 Mango snippets and the standalone editor.');
