const fs=require('node:fs');
const path=require('node:path');
const out=__dirname;
const cssURL='https://cdn.jsdelivr.net/gh/lexdoescodingnow/templates@main/cashew/cashew-curved-line-v1.css';
const gifs=['https://64.media.tumblr.com/6690b9e742b92526354571b1d3d2fad1/bc6f3af8721f1d21-f7/s400x600/6275ef80c0a945f25a981bacda6263da653b3598.gifv','https://64.media.tumblr.com/dc02b622d7671ea63edc93b2a6e30f18/fe1b6e52d8711060-9a/s400x600/053a6dce729fec0bf7ac6b148d2a58ab6b7116b3.gifv'];
const writing={
thread:'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <b>“Aliquam erat volutpat.”</b> Pellentesque vel urna vitae libero blandit lacinia. Maecenas euismod, arcu vitae luctus vestibulum, nibh massa tempus felis, sed pretium sem mi nec augue.</p>\n<p>Donec vitae leo sit amet augue congue malesuada. <i>Nullam id nisi quis justo tincidunt interdum.</i> Sed suscipit, ipsum a volutpat elementum, ante neque luctus quam, at interdum turpis felis vitae metus. Integer non purus sed mi aliquam finibus.</p>\n<p>Curabitur id ligula ac augue sodales congue. <u>Praesent vel velit sed arcu.</u> Cras imperdiet lorem non augue posuere, eu eleifend justo finibus. Suspendisse potenti. Fusce euismod elit eget nibh interdum, sed egestas justo aliquet.</p>',
comms:'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>\n<p><b>Aliquam erat volutpat.</b> Donec vitae leo sit amet augue.</p>\n<p><i>Nullam id nisi quis justo.</i> <u>Praesent vel velit.</u></p>',
bud:'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <b>“Aliquam erat volutpat.”</b> Donec vitae leo sit amet augue congue malesuada. <i>Nullam id nisi quis justo</i> tincidunt interdum. <u>Praesent vel velit</u> sed arcu.</p>'};
const designs=[
['thread','Reniform Reverie','reniform-reverie',1,'where your edges soften','a quiet kind of closeness',1],
['thread','Under the Cashew Tree','under-the-cashew-tree',2,'a place to grow together','beneath the same branches',2],
['thread','Ivory Cotyledon','ivory-cotyledon',1,'the shape of something tender','held between these pages',3],
['thread','Roast Register','roast-register',0,'a little warmth remains','collected, one moment at a time',4],
['thread','Anacardium Nocturne','anacardium-nocturne',2,'the curve that leads to you','when the evening settles',5],
['comms','Cashew Calling','cashew-calling',1,'Yiyun','online now',1],
['comms','Kernelink','kernelink',1,'Cookie','connection secure',3],
['comms','Roastwave','roastwave',1,'Yiyun','new messages',4],
['comms','Shellmail','shellmail',1,'Cookie','active just now',5],
['comms','Caju Connect','caju-connect',2,'Cookie & Yiyun','our little corner',2],
['bud','Seedcurl','seedcurl',1,'stay a little closer','one small moment',1],
['bud','Cashewlet','cashewlet',0,'something to hold','just enough for us',3],
['bud','Ivory Nib','ivory-nib',2,'a word, then another','a note between two',5],
['bud','Toasted Comma','toasted-comma',0,'a pause for you','warmth in the smallest things',4],
['bud','Caju Sprig','caju-sprig',1,'let it begin here','a little room to grow',2]
].map((d,i)=>({type:d[0],name:d[1],slug:d[2],images:d[3],sampleTitle:d[4],subtitle:d[5],motif:d[6],number:String(i%5+1).padStart(2,'0'),file:`cashew-${d[2]}-${d[0]}-${String(i%5+1).padStart(2,'0')}.txt`}));
function esc(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');}
function defaults(d){return {name:'Cookie & Yiyun',url:'[url]',title:d.sampleTitle,subtitle:d.subtitle,gif1:d.images?gifs[d.slug==='kernelink'||d.slug==='shellmail'?1:0]:'',gif2:d.images>1?gifs[1]:'',crop1:'50% 35%',crop2:'50% 35%',copy:writing[d.type],time:'21:08',receipt:'Delivered',direction:'received'};}
function art(n){
const kernel='<path d="M62 14C81 17 89 37 85 54C81 77 60 91 39 84C18 78 8 56 16 41C22 30 35 34 37 44C35 56 41 65 51 63C63 61 66 50 61 42C51 34 49 19 62 14Z" fill="currentColor" fill-opacity=".17" stroke="currentColor" stroke-width="1.8"/><path d="M66 24C79 36 78 54 65 67C51 80 29 70 24 54" fill="none" stroke="currentColor" stroke-width="1.1"/>';
if(n===2)return '<svg viewBox="0 0 120 100" aria-hidden="true"><path class="cw1-leaf" d="M24 76Q59 51 92 15M54 50Q23 46 20 21Q49 23 54 50ZM72 33Q72 7 100 8Q99 30 72 33Z" fill="none" stroke="currentColor" stroke-width="1.2"/><path d="M44 62Q72 47 69 71Q67 87 53 88Q40 87 43 76Q49 72 52 77Q59 81 60 72Q56 67 50 70Q41 72 44 62Z" fill="currentColor" fill-opacity=".25" stroke="currentColor" stroke-width="1.4"/><path d="M50 65L46 59" stroke="currentColor"/></svg>';
if(n===3)return '<svg viewBox="0 0 100 100" aria-hidden="true">'+kernel+'<path d="M57 20L48 34M75 29L62 36M82 48L68 48M75 66L62 57M58 80L55 65M39 78L42 64M22 62L37 56" fill="none" stroke="currentColor" stroke-width=".8"/></svg>';
if(n===4)return '<svg viewBox="0 0 100 100" aria-hidden="true"><path d="M50 7V13M50 87V93M7 50H13M87 50H93M20 20L25 25M75 75L80 80M20 80L25 75M75 25L80 20" stroke="currentColor" stroke-width="1.2"/><g transform="translate(14 14) scale(.72)">'+kernel+'</g></svg>';
if(n===5)return '<svg viewBox="0 0 110 100" aria-hidden="true"><g transform="translate(0 14) scale(.68)">'+kernel+'</g><g transform="translate(110 90) rotate(180) scale(.68)">'+kernel+'</g></svg>';
return '<svg viewBox="0 0 100 100" aria-hidden="true">'+kernel+'</svg>';
}
function template(d,s){
const media=[s.gif1,s.gif2].map((g,i)=>g?`<span class="cw1-shot"><img src="${esc(g)}" alt="Character GIF ${i+1}" style="--cw-crop:${esc(s['crop'+(i+1)])}"></span>`:'').filter(Boolean).join('\n');
const devices={
'cashew-calling':['CASHEW','◦ ◦ ◦','Message…','↑'],
'kernelink':['KERNELINK','CONNECTED','Write a message…','↵'],
'roastwave':['ROASTWAVE','◦ ROASTWAVE ◦','Reply','○'],
'shellmail':['SHELLMAIL','−　□　×','Type a reply…','↗'],
'caju-connect':['CAJU CONNECT','•••','Send a little hello','↑']};
const c=devices[d.slug];
return `[dohtml]\n<div class="cw1 cw1-${d.type} cw1-${d.slug}"${d.type==='comms'?` data-direction="${esc(s.direction)}"`:''}>\n<div class="cw1-layout">\n<div class="cw1-head">\n<a class="cw1-name" href="${esc(s.url)}">${esc(s.name)}</a>\n<span class="cw1-title">${esc(s.title)}</span>\n<span class="cw1-sub">${esc(s.subtitle)}</span>\n</div>\n${media?`<div class="cw1-media">\n${media}\n</div>\n`:''}<div class="cw1-copy">\n${s.copy}\n</div>\n${c?`<div class="cw1-receipt"><span>${esc(s.time)}</span><span>${esc(s.receipt)}</span></div>\n`:''}<div class="cw1-art" aria-hidden="true">${art(d.motif)}</div>\n${c?`<div class="cw1-chrome" aria-hidden="true"><span>${c[0]}</span><span>${c[1]}</span></div>\n<div class="cw1-device" aria-hidden="true"><span>${c[2]}</span><span>${c[3]}</span></div>\n`:''}</div>\n</div>\n<link rel="stylesheet" href="${cssURL}">\n[/dohtml]`;
}
function bare(code){return code.replace(/\[\/?dohtml\]/gi,'').replace(/<link[^>]*>/gi,'');}
const css=fs.readFileSync(path.join(out,'fonts.css'),'utf8')+fs.readFileSync(path.join(out,'layout.css'),'utf8');
fs.writeFileSync(path.join(out,'cashew-curved-line-v1.css'),css);
fs.writeFileSync(path.join(out,'designs.json'),JSON.stringify(designs,null,2)+'\n');
for(const d of designs)fs.writeFileSync(path.join(out,d.file),template(d,defaults(d))+'\n');
fs.writeFileSync(path.join(out,'cashew-placeholder-masterpost.txt'),designs.map(d=>d.name+'\n\n'+template(d,{...defaults(d),name:'[name]',url:'[url]',title:'[text]'})).join('\n\n')+'\n');
const cards=designs.map(d=>{
const s=defaults(d),code=template(d,s);
const fields=[['name','Names'],['url','Link URL'],['title',d.type==='comms'?'Contact / conversation':'Title'],['subtitle',d.type==='comms'?'Status':'Subtitle'],['gif1','GIF 1 URL'],['gif2','GIF 2 URL'],['crop1','GIF 1 position'],['crop2','GIF 2 position'],...(d.type==='comms'?[['time','Time'],['receipt','Receipt']]:[])].map(([key,label])=>`<label>${label}<input name="${key}" value="${esc(s[key])}" spellcheck="false"></label>`).join('');
return `<section class="cw-card" id="${d.slug}" data-kind="${d.type}"><header class="cw-card-head"><span>${d.type==='bud'?'BUDS':d.type.toUpperCase()} / ${d.number}</span><h2>${esc(d.name)}</h2><a href="#top" aria-label="Back to top">↑</a></header><div class="cw-stage">${bare(code)}</div><details class="cw-editor"><summary>Edit this template</summary><form>${fields}${d.type==='comms'?'<label>Message direction<select name="direction"><option value="received">Received</option><option value="sent">Sent</option><option value="alternating">Alternating</option></select></label>':''}<label class="cw-writing">${d.type==='comms'?'Messages':'Writing'}<textarea name="copy" rows="7" spellcheck="false">${esc(s.copy)}</textarea></label><button class="cw-reset" type="button">Reset sample</button></form></details><div class="cw-actions"><button class="cw-copy" type="button">Copy template</button><button class="cw-placeholders" type="button">Copy [name] / [text] version</button><a href="${d.file}">GitHub snippet ↗</a><span class="cw-status" role="status"></span></div><textarea class="cw-code" aria-label="${esc(d.name)} posting code" readonly spellcheck="false">${esc(code)}</textarea></section>`;
}).join('\n');
const page=`<!doctype html>\n<html lang="en" color-mode="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cashew · Cookie &amp; Yiyun</title><style>${css}\n${fs.readFileSync(path.join(out,'preview.css'),'utf8')}</style></head><body><main class="cw-main" id="top"><header class="cw-intro"><div class="cw-collection"><span>COOKIE &amp; YIYUN</span><span>THE CURVED LINE / 15 DESIGNS</span></div><div class="cw-masthead"><h1>Cashew.</h1><span class="cw-emblem">${art(1)}</span></div><nav class="cw-toplinks"><a href="../forum-posts/cashew-forum-masterpost.txt">Forum masterpost ↗</a><a href="cashew-collection.zip">Download collection ↗</a><a href="README.md">Editing guide ↗</a></nav></header><nav class="cw-controls" aria-label="Preview controls"><div class="cw-filters"><button data-filter="all" aria-pressed="true">All 15</button><button data-filter="thread" aria-pressed="false">Threads</button><button data-filter="comms" aria-pressed="false">Comms</button><button data-filter="bud" aria-pressed="false">Buds</button></div><label>Appearance<select id="cw-mode"><option value="light">Light</option><option value="dark">Dark</option><option value="system">System</option></select></label><label>Width<select id="cw-width"><option value="full">Full</option><option value="390">390px</option><option value="320">320px</option><option value="260">260px</option></select></label><label>Member palette<select id="cw-palette"><option value="plum">Plum / jade</option><option value="blue">Blue / lilac</option><option value="copper">Copper / teal</option></select></label></nav>${cards}<footer class="cw-footer">CASHEW / THE CURVED LINE <a href="#top">Back to top ↑</a></footer></main><script>const designs=${JSON.stringify(designs)};const gifs=${JSON.stringify(gifs)};const writing=${JSON.stringify(writing)};const cssURL=${JSON.stringify(cssURL)};${esc.toString()}\n${defaults.toString()}\n${art.toString()}\n${template.toString()}\n${bare.toString()}\n${fs.readFileSync(path.join(out,'preview.js'),'utf8')}</script></body></html>`;
fs.writeFileSync(path.join(out,'cashew-collection-preview.html'),page);
let readme='# Cashew · The Curved Line\n\nFifteen original designs for Cookie & Yiyun: five threads, five device comms and five compact buds.\n\n[Open the editable preview](https://raw.githack.com/lexdoescodingnow/templates/main/cashew/cashew-collection-preview.html) · [Download the preview](https://github.com/lexdoescodingnow/templates/raw/refs/heads/main/cashew/cashew-collection-preview.html) · [Forum masterpost](../forum-posts/cashew-forum-masterpost.txt) · [Complete download](cashew-collection.zip)\n\nEach preview appears above its copyable code. The HTML preview can be downloaded and opened in a browser. On GitHub, use **Copy raw file** on the individual `.txt` snippets.\n\n';
for(const type of ['thread','comms','bud']){readme+=`## ${type==='thread'?'Threads':type==='comms'?'Comms':'Buds'}\n\n| Design | GIFs | Snippet |\n| --- | ---: | --- |\n`;for(const d of designs.filter(d=>d.type===type))readme+=`| ${d.number} · ${d.name} | ${d.images} | [${d.name}](${d.file}) |\n`;readme+='\n';}
readme+='## Editing\n\nNames, link URLs, titles, status, GIFs and paragraph text precede decoration and the single stylesheet link. The snippets and forum copy boxes retain Cookie & Yiyun, the requested Tumblr GIFs and lorem ipsum. [Placeholder variants](cashew-placeholder-masterpost.txt) retain literal `[url]`, `[name]` and `[text]` at the top; the editor has a dedicated copy button for them. No comments, hidden tips or editing notes appear inside posted HTML or CSS.\n\nInside `[dohtml]`, `<b>` / `<strong>`, `<i>` / `<em>`, and `<u>` carry the member gradients. The editor also accepts `[b]`, `[i]`, `[u]` and converts them into HTML when copying. Raw BBCode entered directly in a forum HTML block depends on that forum’s parser. Bold and underline run group 1 → 2 → 3; italics reverse the gradient.\n\nAll frames, heading accents and message borders inherit the forum variables `--mgrgb1`, `--mgrgb2`, `--mgrgb3`. Preview palettes are not copied into posting code. Neutral surfaces follow Blue Hour’s `html[color-mode="light"]` and `html[color-mode="dark"]`; an explicit mode takes precedence over the system preference.\n\nComms use plain `<p>` messages, including successive opening `<p>` tags without closing tags. Change `data-direction` between `received`, `sent`, and `alternating`. Device buttons are decorative. Buds are intended for replies of approximately 100 words or fewer, with no forced text clipping.\n\nClear a GIF field to remove its image or add a URL to include one. For hand edits, remove the image’s `cw1-shot` span; empty media containers collapse. Portrait crop positions are editable via `--cw-crop`, such as `50% 35%`. The image-free Roast Register, Cashewlet and Toasted Comma also accept images.\n\nThe preview embeds all layout CSS and the editor. Fonts and GIFs load online. Forum snippets need no JavaScript; they load one import-free stylesheet, `cashew-curved-line-v1.css`, with embedded font-face definitions. Layouts use modern container queries, `:has()` and `color-mix()`.\n\n## Rebuilding\n\nRun `node cashew/build.cjs`, then `python tools/build_forum_posts.py`, and `python cashew/package.py`. `designs.json` supplies the public names. The Cashew exception in `tools/forum_presentation.py` preserves the requested lorem ipsum in copyable code.\n';
fs.writeFileSync(path.join(out,'README.md'),readme);
console.log('Built 15 Cashew designs, placeholder collection, editable preview, standalone CSS and guide.');
