const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const {JSDOM,VirtualConsole}=require('jsdom');
const csstree=require('css-tree');
const root=__dirname;
const designs=require('./designs.json');
const {raspberryDefaults,raspberryFilename,raspberrySnippet}=require('./raspberry-model.js');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
assert.equal(designs.length,15);
assert.equal(new Set(designs.map(d=>d.name)).size,15);
for(const type of ['thread','comms','bud'])assert.equal(designs.filter(d=>d.type===type).length,5);
const css=read('raspberry-bramble-v1.css');
assert(!css.includes('/*'));
const cssErrors=[];
csstree.parse(css,{onParseError:e=>cssErrors.push(e.message)});
assert.deepEqual(cssErrors,[]);
for(const d of designs){
  const code=read(raspberryFilename(d));
  assert(code.startsWith('[dohtml]\n')&&code.endsWith('[/dohtml]\n'));
  assert(!code.includes('<!--')&&!code.includes('<script'));
  const dom=new JSDOM(code.replace(/^\[dohtml\]|\[\/dohtml\]\s*$/g,''));
  const doc=dom.window.document;
  const wrapper=doc.querySelector('.bh-raspberry');
  assert(wrapper);
  assert.equal(wrapper.children[0].getAttribute('href'),'[url]');
  assert.equal(wrapper.children[0].textContent,'[name]');
  assert.equal(wrapper.children[1].textContent,'[text]');
  assert.equal(doc.querySelectorAll('link[rel="stylesheet"]').length,1);
  assert.equal(doc.querySelectorAll('img').length,d.gifs);
  assert.equal(doc.querySelectorAll('.rby-copy b').length,1);
  assert.equal(doc.querySelectorAll('.rby-copy i').length,1);
  assert.equal(doc.querySelectorAll('.rby-copy u').length,1);
  if(d.type==='bud')assert(doc.querySelector('.rby-copy').textContent.trim().split(/\s+/).length<=100);
  const sample=raspberryDefaults(d);sample.body='<p>One<p><b>Two</b><p>Three';
  const unclosed=new JSDOM(raspberrySnippet(d,sample));
  assert.equal(unclosed.window.document.querySelectorAll('.rby-copy > p').length,3);
  assert.equal(unclosed.window.document.querySelector('.rby-copy').textContent.trim(),'OneTwoThree');
  dom.window.close();unclosed.window.close();
}
const errors=[];
const virtualConsole=new VirtualConsole();
virtualConsole.on('jsdomError',e=>{if(e.type!=='css-parsing')errors.push(e.message)});
const page=new JSDOM(read('raspberry-collection-preview.html'),{runScripts:'dangerously',beforeParse:win=>{win.scrollTo=()=>{}},url:'https://example.invalid/raspberry-preview',virtualConsole});
const w=page.window,doc=w.document,$=s=>doc.querySelector(s);
const input=(sel,value)=>{const e=$(sel);e.value=value;e.dispatchEvent(new w.Event('input',{bubbles:true}));};
const click=sel=>$(sel).click();
assert.equal(doc.querySelectorAll('.pv-choice').length,15);
for(let i=0;i<15;i++){
  doc.querySelectorAll('.pv-choice')[i].click();
  assert.equal($('#pv-code').value,read(raspberryFilename(designs[i])));
  while($('#pv-gifs [data-remove]'))click('#pv-gifs [data-remove]');
  assert.equal($('#pv-stage').querySelectorAll('img').length,0);
  assert(!$('#pv-code').value.includes('rby-media'));
  click('#pv-add-gif');
  assert.equal($('#pv-stage').querySelectorAll('img').length,1);
  assert($('#pv-code').value.includes('7251d36b57319194574408579f5429ac29084941.gifv'));
  input('#pv-name','Jian & Kijoon');
  input('#pv-title','A <new> chapter');
  input('#pv-body','<p>[b]One[/b]<p>[i]Two[/i]<p>[u]Three[/u]');
  assert.equal($('#pv-stage').querySelectorAll('.rby-copy > p').length,3);
  assert.equal($('#pv-stage .rby-title').textContent,'A <new> chapter');
  assert($('#pv-code').value.includes('A &lt;new&gt; chapter'));
  assert(!$('#pv-code').value.includes('[b]'));
  assert.equal($('#pv-stage .rby-copy b').textContent,'One');
  assert.equal($('#pv-stage .rby-copy i').textContent,'Two');
  assert.equal($('#pv-stage .rby-copy u').textContent,'Three');
  if(designs[i].type==='comms'){
    input('#pv-flow','mixed');
    assert.equal($('#pv-stage .bh-raspberry').getAttribute('data-flow'),'mixed');
  }
  input('#pv-body','<p>Hello <script>alert(1)</script><img src=x onerror=alert(2)><a href="javascript:alert(3)">friend</a></p>');
  assert.equal($('#pv-stage .rby-copy').textContent.trim(),'Hello friend');
  assert.equal($('#pv-stage .rby-copy a').getAttribute('href'),'#');
  assert(!$('#pv-code').value.includes('alert('));
  click('#pv-reset');
}
doc.querySelectorAll('.pv-choice')[0].click();
input('#pv-name','Jian & Kijoon');click('#pv-next');click('#pv-previous');
assert.equal($('#pv-name').value,'Jian & Kijoon');
const exported=$('#pv-code').value;
$('#pv-mode').value='dark';$('#pv-mode').dispatchEvent(new w.Event('change'));
assert.equal(doc.documentElement.getAttribute('color-mode'),'dark');
$('#pv-mode').value='system';$('#pv-mode').dispatchEvent(new w.Event('change'));
assert(!doc.documentElement.hasAttribute('color-mode'));
$('#pv-palette').value='lagoon';$('#pv-palette').dispatchEvent(new w.Event('change'));
assert.equal($('#pv-code').value,exported);
assert.equal(doc.documentElement.style.getPropertyValue('--mgrgb1'),'20,133,120');
click('#pv-view-all');assert.equal(doc.querySelectorAll('.pv-tile').length,15);
doc.querySelectorAll('[data-open]')[7].click();
assert.equal($('#pv-design-title').textContent,designs[7].name);
(async()=>{
  let copied='';
  Object.defineProperty(w.navigator,'clipboard',{configurable:true,value:{writeText:async text=>{copied=text}}});
  await $('#pv-copy').onclick();assert.equal(copied,$('#pv-code').value);
  Object.defineProperty(w.navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw Error('Unavailable')}}});
  await $('#pv-copy').onclick();assert($('#pv-code-details').open);
  assert.equal($('#pv-code').selectionEnd,$('#pv-code').value.length);
  assert.deepEqual(errors,[]);
  page.window.close();
  console.log('PASS: 15 snippet structures; CSS syntax; unclosed paragraphs; editor exports, escaping, BBCode conversion, optional GIFs, direction, reset, draft retention, palette isolation, mode controls, gallery and clipboard fallback. Layout rendering is not tested by jsdom.');
})().catch(e=>{console.error(e);process.exitCode=1;page.window.close()});
