const fs=require('node:fs');
const path=require('node:path');
const out=__dirname;
const cssURL='https://cdn.jsdelivr.net/gh/lexdoescodingnow/templates@main/cereal/cereal-first-pour-v1.css';
const gifs=['https://64.media.tumblr.com/6dbb86606de7a352905a1933cb7f8aed/6b0072fb593146dd-4c/s400x600/4ae09aa2881857ab7870aff6da0f06e58198abfc.gifv','https://64.media.tumblr.com/48164030e8190af46fc41c7910f1de9e/099c7f54a5578549-8c/s400x600/2ff312cad77bc77b24ae44d53d2229011afa5b82.gifv'];
const writing={
thread:'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non neque ac lectus faucibus feugiat. <b>“Aliquam erat volutpat, sed tempus nunc.”</b> Duis vitae turpis at erat posuere finibus. Integer quis lorem vel augue consequat volutpat.</p>\n<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae. <i>Etiam a justo quis felis vulputate accumsan.</i> Sed tincidunt, mauris non imperdiet viverra, tellus leo aliquet urna, id pretium lacus enim in erat.</p>\n<p>Nulla facilisi. Proin vitae orci id nibh malesuada interdum. <u>Praesent id augue eget velit.</u> Aenean volutpat nibh at sapien dignissim, sit amet blandit erat interdum. Morbi ornare lectus vitae nibh consequat, quis viverra erat porta.</p>',
comms:'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>\n<p><b>Aliquam erat volutpat.</b> Donec vitae sem ut neque suscipit.</p>\n<p><i>Etiam a justo quis felis.</i> <u>Praesent id augue.</u></p>',
bud:'<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. <b>“Aliquam erat volutpat.”</b> Donec vitae sem ut neque suscipit. <i>Etiam a justo quis felis</i> vulputate accumsan. <u>Praesent id augue</u> eget velit.</p>'};
const designs=[
['thread','Breakfast Club','breakfast-club',2,'stay for breakfast','two servings'],
['thread','Spoon Theory','spoon-theory',1,'the quiet before the day','slow mornings'],
['thread','Prize Inside','prize-inside',0,'something worth keeping','a little surprise'],
['thread','Orbit O’s','orbit-os',2,'always coming back to you','in your orbit'],
['thread','After the Crunch','after-the-crunch',1,'when the world can wait','just us, for a while'],
['comms','Crunchline','crunchline',1,'good morning','messages'],
['comms','Loopback','loopback',1,'you have a message','inbox / 03'],
['comms','Snap Dispatch','snap-dispatch',2,'our conversation','connected'],
['comms','Breakfast Broadcast','breakfast-broadcast',1,'a little wake-up call','messages'],
['comms','Spoonful SMS','spoonful-sms',0,'still here?','online'],
['bud','Little Loop','little-loop',1,'one more minute','just a little'],
['bud','Flakelet','flakelet',0,'a piece of the morning','small comforts'],
['bud','Double Scoop','double-scoop',2,'room for two','side by side'],
['bud','Pocket Prize','pocket-prize',1,'keep this one','a lucky find'],
['bud','Last Cheerio','last-cheerio',0,'the sweetest little thing','one last bite']
].map((d,i)=>({type:d[0],name:d[1],slug:d[2],images:d[3],sampleTitle:d[4],subtitle:d[5],number:String(i%5+1).padStart(2,'0'),file:`cereal-${d[2]}-${d[0]}-${String(i%5+1).padStart(2,'0')}.txt`}));
function esc(v){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');}
function defaults(d){return {name:'Hoseong & Sam',url:'[url]',title:d.sampleTitle,subtitle:d.subtitle,gif1:d.images?gifs[0]:'',gif2:d.images>1?gifs[1]:'',crop1:'50% 35%',crop2:'50% 35%',copy:writing[d.type],time:'08:24',receipt:'Delivered',direction:'received'};}
function template(d,s){
const media=[s.gif1,s.gif2].map((g,i)=>g?`<span class="crl1-shot"><img src="${esc(g)}" alt="${i?'Sam':'Hoseong'} character GIF" style="--cr-crop:${esc(s['crop'+(i+1)])}"></span>`:'').filter(Boolean).join('\n');
const device=d.type==='comms'?`\n<div class="crl1-device" aria-hidden="true"><span>${d.slug==='loopback'?'◁　MENU　▷':d.slug==='breakfast-broadcast'?'Reply':d.slug==='spoonful-sms'?'Write a message…':'Message…'}</span><span>${d.slug==='loopback'?'•••':'↗'}</span></div>`:'';
return `[dohtml]\n<div class="crl1 crl1-${d.type} crl1-${d.slug}"${d.type==='comms'?` data-direction="${esc(s.direction)}"`:''}>\n<div class="crl1-layout">\n<div class="crl1-meta">\n<a href="${esc(s.url)}">${esc(s.name)}</a>\n<span class="crl1-title">${esc(s.title)}</span>\n<span class="crl1-sub">${esc(s.subtitle)}${d.type==='comms'?` · ${esc(s.time)}`:''}</span>\n</div>\n${media?`<div class="crl1-media">\n${media}\n</div>\n`:''}<div class="crl1-copy">\n${s.copy}\n</div>\n${d.type==='comms'?`<div class="crl1-receipt">${esc(s.receipt)}</div>\n`:''}<div class="crl1-art" aria-hidden="true"><span></span><span></span><span></span><span></span><span></span></div>${device}\n</div>\n</div>\n<link rel="stylesheet" href="${cssURL}">\n[/dohtml]`;
}
function bare(code){return code.replace(/\[\/?dohtml\]/gi,'').replace(/<link[^>]*>/gi,'');}
for(const d of designs)fs.writeFileSync(path.join(out,d.file),template(d,defaults(d))+'\n');
fs.writeFileSync(path.join(out,'designs.json'),JSON.stringify(designs,null,2)+'\n');
const markerBlocks=designs.map(d=>d.name+'\n\n'+template(d,{...defaults(d),name:'[name]',url:'[url]',title:'[text]'}));
fs.writeFileSync(path.join(out,'cereal-placeholder-masterpost.txt'),markerBlocks.join('\n\n')+'\n');
const css=fs.readFileSync(path.join(out,'cereal-first-pour-v1.css'),'utf8');
const cards=designs.map(d=>{
 const s=defaults(d),code=template(d,s);
 const fields=[['name','Names'],['url','Link URL'],['title','Title'],['subtitle','Subtitle'],['gif1','GIF 1 URL'],['gif2','GIF 2 URL'],['crop1','GIF 1 position'],['crop2','GIF 2 position'],...(d.type==='comms'?[['time','Time'],['receipt','Receipt']]:[])].map(([key,label])=>`<label>${label}<input name="${key}" value="${esc(s[key])}" spellcheck="false"></label>`).join('');
 return `<section class="cer-card" id="${d.slug}" data-kind="${d.type}"><header class="cer-card-head"><span>${d.type==='bud'?'BUDS':d.type.toUpperCase()} / ${d.number}</span><h2>${esc(d.name)}</h2></header><div class="cer-stage">${bare(code)}</div><details class="cer-editor"><summary>Edit template</summary><form>${fields}${d.type==='comms'?'<label>Message direction<select name="direction"><option value="received">Received</option><option value="sent">Sent</option><option value="alternating">Alternating</option></select></label>':''}<label class="cer-writing">${d.type==='comms'?'Messages':'Writing'}<textarea name="copy" aria-label="${d.type==='comms'?'Messages':'Writing'}" rows="7" spellcheck="false">${esc(s.copy)}</textarea></label><button class="cer-reset" type="button">Reset sample</button></form></details><div class="cer-actions"><button class="cer-copy" type="button">Copy code</button><button class="cer-placeholders" type="button">Copy [name] / [text] version</button><a href="${d.file}">Open snippet</a><span class="cer-status" role="status"></span></div><textarea class="cer-code" aria-label="${esc(d.name)} posting code" readonly spellcheck="false">${esc(code)}</textarea></section>`;
}).join('\n');
const previewCSS=fs.readFileSync(path.join(out,'preview.css'),'utf8');
const js=fs.readFileSync(path.join(out,'preview.js'),'utf8');
const page=`<!doctype html>\n<html lang="en" color-mode="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cereal · Hoseong &amp; Sam</title><style>${css}\n${previewCSS}</style></head><body><main class="cer-main"><header class="cer-intro"><span class="cer-kicker">HOSEONG &amp; SAM / FIRST POUR</span><h1>Cereal<span>15</span></h1><div class="cer-subline"><span>THREADS / COMMS / BUDS</span><a href="../forum-posts/cereal-forum-masterpost.txt">Forum masterpost ↗</a></div></header><nav class="cer-controls" aria-label="Preview controls"><div class="cer-filters"><button data-filter="all" aria-pressed="true">All 15</button><button data-filter="thread" aria-pressed="false">Threads</button><button data-filter="comms" aria-pressed="false">Comms</button><button data-filter="bud" aria-pressed="false">Buds</button></div><label>Mode<select id="cer-mode"><option value="light">Light</option><option value="dark">Dark</option><option value="system">System</option></select></label><label>Preview width<select id="cer-width"><option value="full">Full</option><option value="390">390px</option><option value="320">320px</option><option value="260">260px</option></select></label><label>Member colours<select id="cer-palette"><option value="rose">Rose / olive</option><option value="blue">Blue / violet</option><option value="orange">Orange / teal</option></select></label></nav>${cards}<footer class="cer-footer">CEREAL / FIRST POUR <a href="README.md">Editing guide</a></footer></main><script>const designs=${JSON.stringify(designs)};const gifs=${JSON.stringify(gifs)};const writing=${JSON.stringify(writing)};const cssURL=${JSON.stringify(cssURL)};${esc.toString()}\n${defaults.toString()}\n${template.toString()}\n${bare.toString()}\n${js}</script></body></html>`;
fs.writeFileSync(path.join(out,'cereal-collection-preview.html'),page);
let readme='# Cereal · First Pour\n\nFifteen original designs for Hoseong & Sam: five threads, five device comms and five compact buds.\n\n[Open the live editable preview](https://raw.githack.com/lexdoescodingnow/templates/main/cereal/cereal-collection-preview.html) · [Download the editor](https://github.com/lexdoescodingnow/templates/raw/refs/heads/main/cereal/cereal-collection-preview.html) · [Forum masterpost](../forum-posts/cereal-forum-masterpost.txt) · [Complete Cereal download](cereal-collection.zip)\n\nDownload the HTML preview and open it in your browser to view, edit and copy. GitHub itself displays the HTML source. Individual `.txt` files below can be copied directly with GitHub’s **Copy raw file** button.\n\n';
for(const type of ['thread','comms','bud']){
readme+=`## ${type==='thread'?'Threads':type==='comms'?'Comms':'Buds'}\n\n| Design | GIFs | Snippet |\n| --- | ---: | --- |\n`;
for(const d of designs.filter(d=>d.type===type))readme+=`| ${d.number} · ${d.name} | ${d.images} | [${d.name}](${d.file}) |\n`;
readme+='\n';}
readme+='## Editing\n\nEditable names, `[url]`, titles, GIF URLs and writing are at the top of each block; decoration and the single shared stylesheet link come last. Default snippets contain Hoseong & Sam, the supplied Tumblr GIFs and lorem ipsum, including in the forum masterpost’s copy boxes. The [placeholder versions](cereal-placeholder-masterpost.txt) keep `[url]`, `[name]` and `[text]` at the top with the same GIFs and sample writing. The editor also has a separate button to copy these fields as placeholders. No editing comments or hidden tips are included in the posted HTML or CSS.\n\nInside `[dohtml]`, use `<b>`, `<i>`, `<u>` (or `<strong>`, `<em>`). The editor converts `[b]`, `[i]` and `[u]` before exporting. Direct BBCode inside a forum HTML block depends on the forum parser; these snippets need no JavaScript to display. Bold and underline use the forward member gradient; italics reverse it.\n\nAll headers, frames, borders and decorative accents inherit `--mgrgb1`, `--mgrgb2`, `--mgrgb3`. Preview palettes never appear in copied snippets. Neutral backgrounds follow Blue Hour’s `html[color-mode="light"]` and `html[color-mode="dark"]`; explicit forum mode overrides system preference.\n\nComms use separate plain `<p>` messages; successive opening tags work without closing tags. Set `data-direction` to `received`, `sent` or `alternating`. Device controls are decorative. Buds are miniature threads for replies of around 100 words or fewer and expand naturally for longer writing.\n\nGIFs can be added or removed in any design. Clear a GIF field or remove its entire `crl1-shot` span; remove the empty media container if editing by hand. Layouts reclaim empty portrait space. Crop positions are editable percentages, defaulting to `50% 35%`. No text areas have a fixed height.\n\nThe standalone preview includes its CSS and editor; GIFs need internet access. Posted templates load one import-free stylesheet from `@main/cereal/cereal-first-pour-v1.css`, with system fonts and CSS-drawn motifs. Modern `:has()`, container queries and `color-mix()` are used.\n\n## Rebuilding\n\nRun `node cereal/build.cjs`, then `python tools/build_forum_posts.py` and `python cereal/package.py`. The Cereal exception in `tools/forum_presentation.py` preserves the user-requested lorem ipsum in copyable code. `designs.json` supplies public names to the master catalogue.\n';
fs.writeFileSync(path.join(out,'README.md'),readme);
console.log('Built 15 Cereal templates, placeholder collection, editor, manifest and guide.');
